const express = require('express')
const app = express()
const cors = require('cors')
const PORT = 8000

app.use(cors())


const card = {
  'the fool': {
    'cardName': 'The Fool',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '0',
    'romanCardNum': 'O',
    'description': 'The Fool card is a daring leap into the unknown, representing new beginnings and boundless potential. With carefree abandon, the Fool sets off on a whimsical adventure, unaware of the challenges ahead. Symbolizing innocence and spontaneity, the Fool encourages us to embrace curiosity and take risks. It is a call to trust the journey, follow our instincts, and have faith in the unfolding path. The Fool reminds us that sometimes the greatest wisdom comes from embracing the foolishness of exploration and embracing the magic of life\'s surprises.',
    'upright1': 'Spontaneity: The Fool upright represents a carefree and spontaneous nature. It is associated with taking risks and embracing new adventures without fear or hesitation.',
    'upright2': 'Innocence: The Fool embodies a sense of childlike innocence and naivety. It suggests a lack of preconceived notions or biases, allowing for a fresh perspective and open-mindedness.',
    'upright3': 'Optimism: This card radiates positivity and optimism. The Fool upright encourages a hopeful outlook on life, emphasizing the belief that everything will work out for the best.',
    'upright4': 'Freedom: The Fool symbolizes freedom from constraints and limitations. It signifies a willingness to break free from societal norms or expectations, embracing personal freedom and individuality.',
    'upright5': 'Beginnings: The Fool is associated with new beginnings and fresh starts. It represents the start of a journey or a new phase in life, urging you to embrace change and take the first steps towards your goals.',
    'reversed1': 'Recklessness: The Fool reversed indicates a lack of caution or thoughtfulness in your actions. It suggests impulsive behavior and a tendency to act without considering the consequences.',
    'reversed2': 'Foolishness: In the reversed position, the Fool represents poor judgment or decision-making. It signifies a lack of wisdom or understanding, leading to unwise choices or actions.',
    'reversed3': 'Naivety: The Fool reversed suggests a state of being overly trusting or gullible. It signifies a vulnerability to deception or manipulation, as well as a tendency to overlook important details or warning signs.',
    'reversed4': 'Stagnation: This card in reverse can indicate a resistance to change or a fear of taking risks. It suggests a reluctance to embrace new opportunities or step out of your comfort zone, leading to a sense of stagnation or missed chances.',
    'reversed5': 'Consequences: The Fool reversed often signifies facing the consequences of your actions or decisions. It warns of potential setbacks, misunderstandings, or negative outcomes resulting from hasty or ill-considered choices.',
    'img': '/img/the-fool.png',
  },
  'the magician': {
    'cardName': 'The Magician',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '1',
    'romanCardNum': 'I',
    'description': 'The Magician card wields the power of manifestation and transformation. With one hand pointing upward and the other downward, he bridges the realms of spirit and matter. The Magician channels cosmic energy, using it to shape his reality. He symbolizes the creative force within us, reminding us of our innate ability to manifest our desires. Through mastery of the elements, he transforms dreams into tangible achievements. The Magician invites us to harness our personal power, align with the universe, and embark on a journey of limitless possibilities.',
    'upright1': 'Mastery: The Magician upright represents a mastery of skills and abilities. It signifies having the knowledge, expertise, and confidence to manifest your desires and goals effectively.',
    'upright2': 'Creativity: This card symbolizes creative energy and the power of imagination. The Magician encourages innovative thinking and resourcefulness in finding unique solutions to challenges.',
    'upright3': 'Manifestation: The Magician upright embodies the ability to manifest your intentions into reality. It signifies the power of focused intention, willpower, and taking action to bring about desired outcomes.',
    'upright4': 'Transformation: The Magician represents a transformative energy that facilitates personal growth and positive change. It suggests harnessing your inner potential and embracing opportunities for self-improvement.',
    'upright5': 'Alignment: This card signifies the alignment of mind, body, and spirit. The Magician upright encourages individuals to tap into your inner wisdom and connect with your higher selves, creating a harmonious balance within yourself and your surroundings.',
    'reversed1': 'Manipulation: The Magician reversed can indicate a tendency towards manipulation or deceit. It suggests the misuse of power or skills for personal gain, leading to dishonesty or trickery.',
    'reversed2': 'Lack of Focus: In the reversed position, the Magician represents a lack of focus or direction. It suggests scattered energy and an inability to harness your abilities effectively, resulting in a lack of progress or achievement.',
    'reversed3': 'Misuse of Power: This card signifies the misuse or abuse of power. It suggests that you may be using your skills or influence in a negative or harmful way, potentially causing harm to others or themselves.',
    'reversed4': 'Ineffectiveness: The Magician reversed represents a lack of effectiveness or inefficiency in your actions. It suggests that despite having the necessary skills or resources, you are unable to utilize them effectively, leading to unsuccessful outcomes or missed opportunities.',
    'reversed5': 'Blocked Potential: This card in reverse can indicate a blockage or suppression of your potential. It suggests a failure to tap into your true abilities or talents, resulting in a sense of stagnation or unfulfilled potential.',
    'img': '',
  },
  'the high priestess': {
    'cardName': 'The High Priestess',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '2',
    'romanCardNum': 'II',
    'description': 'The High Priestess card is a mystical gatekeeper, revealing the secrets of the unseen. Seated between two pillars, she embodies intuition, wisdom, and the connection to the divine. Veiled in mystery, she guards esoteric knowledge and guides seekers on their spiritual journey. The High Priestess symbolizes the depths of our subconscious, urging us to trust our intuition and explore the hidden realms of our inner wisdom. With her guidance, we unlock the sacred mysteries, access higher realms of consciousness, and discover profound truths that transcend the mundane.',
    'upright1': 'Intuition: The High Priestess upright represents deep intuition and inner wisdom. It suggests the ability to tap into your subconscious mind and access intuitive insights and knowledge.',
    'upright2': 'Mystery: This card embodies a sense of mystery and hidden knowledge. The High Priestess signifies the presence of secrets, hidden truths, and esoteric wisdom that may be revealed over time.',
    'upright3': 'Feminine Energy: The High Priestess is associated with feminine energy and the divine feminine. It represents intuition, receptivity, and the nurturing aspects of your nature.',
    'upright4': 'Spiritual Connection: This card symbolizes a strong connection to the spiritual realm. It suggests a deep understanding of spiritual matters, meditation, and inner reflection to gain spiritual insights and guidance.',
    'upright5': 'Inner Balance: The High Priestess upright signifies inner balance and harmony. It suggests a state of equilibrium between the conscious and subconscious mind, embracing both rationality and intuition in decision-making and life choices.',
    'reversed1': 'Blocked Intuition: The High Priestess reversed suggests a blockage or suppression of your intuition. It indicates a lack of trust in your inner wisdom and an inability to access or heed intuitive guidance.',
    'reversed2': 'Hidden Knowledge: In the reversed position, the High Priestess represents hidden or obscured knowledge that remains out of reach. It suggests a difficulty in uncovering deeper truths or accessing esoteric wisdom.',
    'reversed3': 'Lack of Understanding: This card signifies a lack of understanding or confusion. The High Priestess reversed suggests a struggle to grasp the deeper meaning or significance of certain experiences or situations.',
    'reversed4': 'Disconnection from Spirituality: In the reversed position, the High Priestess indicates a disconnection from spirituality or a lack of spiritual exploration. It suggests a diminished connection to your higher self and a disregard for inner reflection or spiritual practices.',
    'reversed5': 'Imbalance: The High Priestess reversed suggests an imbalance between the conscious and subconscious mind. It signifies a lack of inner harmony, where rationality and intuition are at odds, leading to confusion or indecisiveness.',
    'img': '',
  },
  'the empress': {
    'cardName': 'The Empress',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '3',
    'romanCardNum': 'III',
    'description': 'The Empress card is a radiant embodiment of fertility, abundance, and nurturing energy. Seated on a throne surrounded by lush nature, she represents the bountiful mother archetype. The Empress nurtures creativity and creation, inviting us to connect with our sensual and nurturing sides. She symbolizes the power of feminine energy, the beauty of nature, and the cycle of life. With the Empress, we find harmony in embracing our nurturing qualities, tapping into our creativity, and honoring the abundance that surrounds us.',
    'upright1': 'Fertility: The Empress upright represents fertility, both in terms of physical fertility and the ability to nurture and create. It signifies a time of abundance, growth, and the potential for new beginnings.',
    'upright2': 'Nurturing: This card embodies nurturing and maternal energy. The Empress signifies a caring and compassionate nature, offering support and guidance to others. It represents the ability to create a loving and nurturing environment.',
    'upright3': 'Creativity: The Empress upright symbolizes creativity and artistic expression. It suggests a time of inspiration and the birth of new ideas. This card encourages embracing your creative abilities and exploring artistic endeavors.',
    'upright4': 'Abundance: This card represents abundance and prosperity. The Empress signifies a time of material and emotional abundance, where resources and opportunities are readily available. It suggests a sense of wealth and fulfillment.',
    'upright5': 'Harmony: The Empress upright signifies harmony and balance. It represents a state of equilibrium and contentment, where you feels connected to the natural rhythms of life. This card suggests finding harmony within yourself and in relationships with others.',
    'reversed1': 'Lack of Nurturing: The Empress reversed suggests a lack of nurturing or neglectful behavior. It signifies a failure to provide care and support to yourself or others. It may indicate difficulties in creating a loving and nurturing environment.',
    'reversed2': 'Creative Block: In the reversed position, the Empress represents a creative block or a struggle to express yourself artistically. It suggests a lack of inspiration or difficulty in manifesting creative ideas.',
    'reversed3': 'Scarcity: This card indicates a sense of scarcity or a lack of abundance. The Empress reversed signifies a period of limited resources, both material and emotional. It may suggest financial challenges or a feeling of emptiness.',
    'reversed4': 'Disharmony: The Empress reversed represents disharmony and imbalance. It suggests a lack of harmony within yourself or in relationships. It may indicate conflicts, discord, or a sense of disconnection from the natural rhythms of life.',
    'reversed5': 'Self-neglect: This card suggests self-neglect or a disregard for self-care. The Empress reversed signifies a tendency to put others\' needs before your own, leading to a depletion of energy and a lack of personal fulfillment.',
    'img': '',
  },
  'the emperor': {
    'cardName': 'The Emperor',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '4',
    'romanCardNum': 'IV',
    'description': 'The Emperor card exudes the commanding presence of leadership and authority. Seated on a throne, the Emperor wears a crown and holds a scepter, symbolizing his dominion and control. He represents structure, stability, and the power to manifest ambitions. The Emperor inspires us to embrace our inner sovereignty, take charge of our lives, and build solid foundations. With his guidance, we navigate the realms of responsibility, establish order, and tap into our innate ability to shape our world. The Emperor reminds us that with strength, strategy, and decisive action, we can conquer any challenge.',
    'upright1': 'Authority: The Emperor upright represents authority and leadership. It symbolizes a strong and confident individual who is capable of taking charge and making decisions with clarity and conviction.',
    'upright2': 'Structure: This card embodies structure and organization. The Emperor signifies the establishment of order and systems, providing a solid foundation for stability and success.',
    'upright3': 'Power: The Emperor upright signifies personal power and control. It represents the ability to assert yourself and influence your surroundings, displaying strength and resilience in the face of challenges.',
    'upright4': 'Discipline: This card represents discipline and self-control. The Emperor signifies the importance of setting boundaries, adhering to rules, and maintaining a focused approach in order to achieve goals.',
    'upright5': 'Responsibility: The Emperor upright embodies responsibility and accountability. It signifies taking on leadership roles, fulfilling obligations, and being accountable for your actions and decisions. This card emphasizes the need for wise and responsible governance.',
    'reversed1': 'Authoritarianism: The Emperor reversed suggests a misuse or abuse of authority. It signifies a tendency towards oppressive or dictatorial behavior, where power is exercised in a domineering or controlling manner.',
    'reversed2': 'Lack of Structure: In the reversed position, the Emperor represents a lack of structure or disorganization. It signifies a difficulty in establishing and maintaining order, leading to chaos or instability.',
    'reversed3': 'Power Struggles: This card suggests power struggles or challenges to authority. The Emperor reversed signifies conflicts or resistance to established leadership, often resulting from a lack of trust or dissatisfaction with the current structure.',
    'reversed4': 'Lack of Discipline: In the reversed position, the Emperor signifies a lack of discipline or self-control. It suggests a tendency towards impulsiveness or erratic behavior, leading to a lack of focus or direction.',
    'reversed5': 'Irresponsibility: The Emperor reversed embodies a lack of responsibility or accountability. It suggests an avoidance of leadership roles or a failure to fulfill obligations and duties. This card highlights a lack of maturity or unwillingness to take on necessary responsibilities.',
    'img': '',
  },
  'the hierophant': {
    'cardName': 'The Hierophant',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '5',
    'romanCardNum': 'V',
    'description': 'The Hierophant card embodies the wisdom of tradition and spiritual guidance. A figure sits on a throne, holding a staff of authority and wearing sacred symbols. It represents the bridge between the earthly and the divine, offering teachings and rituals for spiritual growth. The Hierophant invites us to seek wisdom from established systems, honor traditions, and embrace the guidance of mentors. It symbolizes the power of collective knowledge and the transformative potential of connecting with higher wisdom. Through the Hierophant, we find solace in ancient wisdom and the path of spiritual enlightenment.',
    'upright1': 'Tradition: The Hierophant upright represents tradition and conformity. It signifies adherence to established norms, rituals, and cultural or religious customs.',
    'upright2': 'Spiritual Guidance: This card embodies spiritual guidance and wisdom. The Hierophant signifies the presence of a spiritual teacher or mentor who imparts valuable knowledge and guidance on matters of spirituality and belief systems.',
    'upright3': 'Authority: The Hierophant upright signifies authority and leadership in spiritual or religious matters. It represents an individual or institution with a significant role in providing guidance, interpreting doctrines, or upholding religious teachings.',
    'upright4': 'Conformity: This card suggests a need for conformity or adherence to societal norms. The Hierophant signifies a desire to fit in or seek validation through adhering to established structures and belief systems.',
    'upright5': 'Rituals and Ceremonies: The Hierophant upright embodies rituals, ceremonies, and formalities. It represents the importance of participating in meaningful rituals or ceremonies to foster spiritual connection and growth. This card emphasizes the significance of tradition and shared experiences within a community or group. ',
    'reversed1': 'Nonconformity: The Hierophant reversed signifies a rejection of traditional norms and a resistance to conformity. It suggests a desire to break free from established structures and explore alternative paths or belief systems.',
    'reversed2': 'Unconventional Spirituality: In the reversed position, the Hierophant represents a departure from mainstream spirituality or organized religion. It suggests a personal exploration of spirituality that diverges from established practices or doctrines.',
    'reversed3': 'Questioning Authority: This card suggests a skepticism towards authority figures or institutions. The Hierophant reversed signifies a tendency to question the teachings and guidance of traditional authorities, seeking your own truths and beliefs.',
    'reversed4': 'Unorthodox Practices: The Hierophant reversed embodies unorthodox or alternative practices. It represents a willingness to explore different spiritual paths or unconventional methods of seeking enlightenment or inner wisdom.',
    'reversed5': 'Spirituality in Personal Terms: This card suggests an individualized approach to spirituality. The Hierophant reversed signifies the importance of finding your own spiritual path and defining your beliefs and practices based on personal experiences and insights.',
    'img': '',
  },
  'the lovers': {
    'cardName': 'The Lovers',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '6',
    'romanCardNum': 'VI',
    'description': 'The Lovers card radiates with the power of divine connection and sacred union. Two figures, joined by love and destiny, stand under the watchful gaze of an angel. It represents the merging of opposites, the harmony of relationships, and the choices that shape our lives. The Lovers inspire us to seek deep soul connections, honor our passions, and embrace the transformative power of love. It reminds us that love is both a profound gift and a profound responsibility, inviting us to embark on a journey of shared growth and spiritual evolution.',
    'upright1': 'Love: The Lovers upright represents love in all its forms, including romantic love, deep connections, and harmonious relationships. It signifies a union of hearts and a deep emotional bond.',
    'upright2': 'Partnership: This card embodies partnership and companionship. The Lovers signify the coming together of two individuals in a mutually supportive and loving relationship, emphasizing the importance of collaboration and cooperation.',
    'upright3': 'Choices: The Lovers upright signifies choices and decisions related to love and relationships. It represents the need to make thoughtful and conscious choices that align with your values and desires.',
    'upright4': 'Harmony: This card represents harmony and balance within relationships. The Lovers signify a sense of unity, where differences are embraced, and love prevails. It suggests the potential for deep emotional connection and understanding.',
    'upright5': 'Alignment: The Lovers upright embodies alignment and soul connection. It signifies finding a partner or relationship that aligns with your true self and values, emphasizing the importance of authenticity and emotional compatibility.',
    'reversed1': 'Disharmony: The Lovers reversed suggests disharmony and discord in relationships. It represents a lack of alignment or compatibility between partners, leading to conflicts and misunderstandings.',
    'reversed2': 'Choices and Indecision: In the reversed position, the Lovers symbolize indecision or difficulty in making choices related to love and relationships. It signifies a struggle in committing or deciding between different options.',
    'reversed3': 'Unhealthy Attachments: This card suggests unhealthy attachments or codependency. The Lovers reversed represents relationships characterized by a lack of independence and a reliance on the other person for validation or self-worth.',
    'reversed4': 'Love Blocks: The Lovers reversed signifies blocks or obstacles to experiencing love and deep connections. It suggests barriers in opening up emotionally or difficulties in forming meaningful relationships.',
    'reversed5': 'Dishonesty: This card represents dishonesty or deceit within relationships. The Lovers reversed signifies a lack of transparency or trust, indicating potential betrayal or hidden agendas. It serves as a warning to be cautious and aware of potential deception.',
    'img': '',
  },
  'the chariot': {
    'cardName': 'The Chariot',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '7',
    'romanCardNum': 'VII',
    'description': 'The Chariot card charges forward with unwavering determination, symbolizing triumph and willpower. A figure stands tall in a chariot, pulled by opposing forces, guiding them in perfect harmony. It represents the balance of opposing energies and harnessing them to achieve victory. The Chariot reminds us to align our desires and ambitions, focusing our energy and setting a clear course. It embodies the spirit of conquest, urging us to overcome obstacles, navigate challenges, and emerge victorious on our chosen path. With the Chariot, we embrace the exhilarating journey of self-mastery and achievement.',
    'upright1': 'Determination: The Chariot upright represents determination and willpower. It signifies a strong sense of purpose and the drive to overcome obstacles and achieve success.',
    'upright2': 'Control: This card embodies control and mastery over your circumstances. The Chariot signifies the ability to navigate through challenges and maintain a sense of control and direction in life.',
    'upright3': 'Victory: The Chariot upright signifies victory and triumph. It represents achieving desired outcomes and reaching your goals through focused effort and perseverance.',
    'upright4': 'Ambition: This card symbolizes ambition and drive for success. The Chariot signifies a strong desire to achieve greatness and make progress towards personal and professional aspirations.',
    'upright5': 'Forward Movement: The Chariot represents forward movement and progress. It signifies a period of advancement and momentum, propelling you towards your desired destination or future endeavors.',
    'reversed1': 'Lack of Direction: The Chariot reversed suggests a lack of direction or clarity in your goals and aspirations. It signifies a feeling of being lost or uncertain about the path ahead.',
    'reversed2': 'Lack of Control: In the reversed position, the Chariot represents a loss of control or a struggle to maintain stability. It suggests difficulties in managing challenges or external forces that hinder progress.',
    'reversed3': 'Lack of Motivation: This card signifies a lack of motivation or drive. The Chariot reversed suggests a loss of ambition or energy, resulting in a lack of progress or the inability to move forward.',
    'reversed4': 'Inner Conflict: The Chariot reversed represents inner conflict or internal battles. It signifies a struggle between different desires or motivations, leading to indecisiveness or a lack of alignment within yourself.',
    'reversed5': 'Stagnation: This card suggests stagnation or a lack of forward movement. The Chariot reversed signifies being stuck in a state of inertia, where progress and growth are hindered, leading to a sense of frustration or being stuck in a rut.',
    'img': '',
  },
  'strength': {
    'cardName': 'Strength',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '8',
    'romanCardNum': 'VIII',
    'description': 'The Strength card embodies the power of courage and resilience in the face of adversity. A figure gently tames a mighty lion, demonstrating inner strength and mastery of primal instincts. It symbolizes the triumph of compassion over aggression, and the ability to harness inner fortitude. Strength invites us to confront challenges with grace, embrace our inner power, and find the courage to overcome obstacles. It reminds us that true strength lies not in brute force, but in the gentle yet unwavering resolve of the human spirit.',
    'upright1': 'Inner Strength: The Strength upright represents inner strength and courage. It signifies the ability to face challenges with resilience, confidence, and determination.',
    'upright2': 'Courage: This card embodies courage and bravery. The Strength card signifies the willingness to confront fears, overcome obstacles, and stand up for what is right.',
    'upright3': 'Patience: The Strength card symbolizes patience and endurance. It represents the ability to remain calm and composed in the face of adversity, waiting for the right moment to take action.',
    'upright4': 'Compassion: This card signifies compassion and gentleness. The Strength card represents the power of love and understanding, using empathy and kindness to resolve conflicts and build bridges.',
    'upright5': 'Self-Mastery: The Strength upright embodies self-mastery and self-control. It signifies the ability to harness your passions and instincts, channeling them in a positive and balanced way. It represents inner harmony and taming your inner "wild" aspects.',
    'reversed1': 'Lack of Confidence: The Strength reversed suggests a lack of confidence or self-belief. It signifies doubts and insecurities that hinder your ability to face challenges or overcome obstacles.',
    'reversed2': 'Inner Turmoil: In the reversed position, the Strength card represents inner turmoil or a struggle with your emotions. It suggests a lack of emotional stability or difficulty in managing and harnessing your passions and instincts.',
    'reversed3': 'Weakness: This card signifies weakness or a lack of inner strength. The Strength reversed suggests a vulnerability to external pressures or an inability to stand up for yourself in the face of adversity.',
    'reversed4': 'Self-Doubt: The Strength reversed represents self-doubt and a lack of self-trust. It signifies a lack of belief in your abilities or a tendency to underestimate your own power and potential.',
    'reversed5': 'Unresolved Conflict: This card suggests unresolved conflicts or power struggles. The Strength reversed signifies a difficulty in finding a resolution or maintaining inner harmony in challenging situations. It may indicate a need to address and confront these conflicts to regain personal strength.',
    'img': '',
  },
  'the hermit': {
    'cardName': 'The Hermit',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '9',
    'romanCardNum': 'IX',
    'description': 'The Hermit card beckons you to seek solitude and introspection in the depths of your inner sanctuary. A cloaked figure holds a lantern, guiding the way through darkness and uncertainty. The Hermit represents wisdom gained through introspection and the quest for deeper understanding. It symbolizes inner guidance, soul-searching, and a retreat from the noise of the world. In the solitude of the Hermit\'s embrace, you discover profound truths, connect with your inner wisdom, and find the light that illuminates your path forward.',
    'upright1': 'Solitude: The Hermit upright represents solitude and introspection. It signifies a period of seeking inner wisdom and guidance through solitude and self-reflection.',
    'upright2': 'Wisdom: This card embodies wisdom and knowledge. The Hermit signifies the pursuit of deeper understanding, drawing on personal experience and accumulated wisdom to navigate life\'s challenges.',
    'upright3': 'Inner Guidance: The Hermit upright signifies the importance of listening to your inner voice and trusting your intuition. It represents seeking guidance from within and following your own unique path.',
    'upright4': 'Spiritual Quest: This card symbolizes a spiritual quest or journey. The Hermit represents a period of seeking spiritual enlightenment, finding deeper meaning, and connecting with higher truths.',
    'upright5': 'Mentorship: The Hermit upright suggests the presence of a wise mentor or teacher. It signifies the guidance and support of someone with profound knowledge and experience, aiding in personal growth and self-discovery.',
    'reversed1': 'Isolation: The Hermit reversed suggests a prolonged state of isolation or social withdrawal. It represents a disconnection from others and a reluctance to seek or accept external help or guidance.',
    'reversed2': 'Loneliness: In the reversed position, the Hermit signifies feelings of loneliness or a sense of being cut off from the world. It suggests a lack of meaningful connections or difficulty in forming relationships.',
    'reversed3': 'Lost Direction: This card represents a loss of direction or purpose. The Hermit reversed suggests a feeling of being lost or confused, with a lack of clarity about your path or goals.',
    'reversed4': 'Avoidance: The Hermit reversed signifies a tendency to avoid introspection or self-reflection. It suggests a resistance to facing inner truths or avoiding necessary periods of solitude and introspection for personal growth.',
    'reversed5': 'Lack of Guidance: In the reversed position, the Hermit indicates a lack of guidance or mentorship. It suggests a difficulty in finding wise counsel or seeking guidance from others, leading to a sense of uncertainty or feeling adrift.',
    'img': '',
  },
  'wheel of fortune': {
    'cardName': 'Wheel Of Fortune',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '10',
    'romanCardNum': 'X',
    'description': 'The Wheel of Fortune card spins the wheel of destiny, bringing cycles of change and opportunity. It represents the ebb and flow of life, where fortunes rise and fall. A wheel turns, adorned with mysterious symbols, as figures ascend and descend. The Wheel reminds us of the ever-changing nature of existence and the power of fate. It teaches us to embrace uncertainty, seize favorable moments, and adapt to life\'s inevitable twists and turns. With the Wheel of Fortune, we find that our choices and actions can shape our destiny as we ride the cosmic wheel of time.',
    'upright1': 'Destiny: The Wheel of Fortune upright represents the concept of destiny and the unfolding of fate. It signifies that life is governed by cycles of ups and downs and that events are influenced by factors beyond our control.',
    'upright2': 'Change: This card embodies change and transformation. The Wheel of Fortune signifies that life is constantly evolving, and situations can shift unexpectedly. It represents embracing change and being open to new opportunities.',
    'upright3': 'Luck: The Wheel of Fortune upright symbolizes luck and fortune. It suggests that favorable circumstances or unexpected opportunities may arise in your life, bringing positive outcomes.',
    'upright4': 'Cycles: This card represents the cyclical nature of life. The Wheel of Fortune signifies that everything in life operates in cycles, with periods of growth, decline, and renewal. It emphasizes the importance of understanding and accepting these cycles.',
    'upright5': 'Synchronicity: The Wheel of Fortune signifies synchronicity and the interplay of events and energies in the universe. It suggests that there are underlying connections and meaningful coincidences at play, guiding your path and aligning with the flow of life.',
    'reversed1': 'Stagnation: The Wheel of Fortune reversed suggests a state of stagnation or feeling stuck. It represents a lack of progress or difficulty in moving forward due to external or internal factors.',
    'reversed2': 'Resistance to Change: In the reversed position, this card signifies resistance to change. It suggests a reluctance to embrace the natural cycles of life or a fear of stepping into the unknown.',
    'reversed3': 'Unpredictability: The Wheel of Fortune reversed symbolizes unpredictability and a lack of control over external circumstances. It indicates that events may be more chaotic or uncertain, making it challenging to anticipate or navigate through them.',
    'reversed4': 'Misfortune: This card represents a period of misfortune or unfortunate events. The Wheel of Fortune reversed suggests that luck may not be in your favor, and unexpected challenges or setbacks may arise.',
    'reversed5': 'Breaking Cycles: In the reversed position, the Wheel of Fortune signifies an opportunity to break negative cycles or patterns. It suggests a need for conscious awareness and deliberate action to create positive change and break free from repetitive cycles of outcomes.',
    'img': '',
  },
  'justice': {
    'cardName': 'Justice',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '11',
    'romanCardNum': 'XI',
    'description': 'The Justice card embodies the scales of truth, impartiality, and balance. A figure holds a sword and scales, symbolizing the pursuit of justice and fairness. It represents the cosmic law of cause and effect, urging us to take responsibility for our actions. Justice calls for integrity, ethical decisions, and the restoration of equilibrium. It reminds us that actions have consequences and that true justice lies in aligning our actions with our values. Through the lens of Justice, we find harmony and the assurance that fairness will prevail.',
    'upright1': 'Fairness: The Justice upright represents fairness and impartiality. It signifies the need for balance and equality in all aspects of life, including decision-making, relationships, and justice systems.',
    'upright2': 'Accountability: This card embodies accountability and taking responsibility for your actions. The Justice card signifies the consequences and repercussions of your choices and behaviors.',
    'upright3': 'Truth: The Justice card represents truth and honesty. It signifies the importance of seeking and upholding truth, both within yourself and in external situations. It emphasizes the power of integrity and transparency.',
    'upright4': 'Legal Matters: This card is associated with legal matters and the justice system. The Justice upright signifies the need for legal proceedings to be conducted fairly, and it can suggest positive outcomes or resolutions in legal disputes.',
    'upright5': 'Balancing Choices: The Justice card represents the need to weigh options and make balanced decisions. It signifies the importance of considering different perspectives and finding a middle ground when faced with conflicting choices or situations.',
    'reversed1': 'Unfairness: The Justice reversed suggests unfairness and imbalance. It signifies situations where justice is compromised or where decisions and actions lack fairness and impartiality.',
    'reversed2': 'Dishonesty: In the reversed position, the Justice card represents dishonesty or deceit. It suggests the presence of lies, deception, or manipulation in a situation, making it challenging to find truth and uphold justice.',
    'reversed3': 'Lack of Accountability: This card signifies a lack of accountability or evasion of responsibility. The Justice reversed suggests a refusal to take ownership of your actions or face the consequences of your choices.',
    'reversed4': 'Legal Injustice: The Justice reversed can represent legal injustice or unfair legal outcomes. It suggests that legal proceedings may be biased, unjust, or improperly conducted, leading to unjust results.',
    'reversed5': 'Imbalance: This card embodies imbalance and lack of equilibrium. The Justice reversed signifies situations where there is a lack of fairness, harmony, or balance. It may indicate a need to restore balance and rectify injustices.',
    'img': '',
  },
  'the hanged man': {
    'cardName': 'The Hanged Man',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '12',
    'romanCardNum': 'XII',
    'description': 'The Hanged Man card defies expectations, inviting you to see the world from a different perspective. Suspended upside down, a figure finds surrender in a moment of suspended grace. It symbolizes sacrifice, letting go, and gaining enlightenment through surrender. The Hanged Man challenges you to embrace stillness, explore alternative viewpoints, and find wisdom in moments of pause. In the surrender of control, you discover profound insights, new paths, and the transformative power of shifting your perception. Embrace the suspended state and trust in the hidden blessings it holds.',
    'upright1': 'Surrender: The Hanged Man upright represents surrender and letting go. It signifies the willingness to release control, expectations, and attachments in order to gain a new perspective or insight.',
    'upright2': 'Suspension: This card embodies suspension and a state of pause or waiting. The Hanged Man signifies a period of introspection and contemplation, where you may need to step back from action and observe from a different vantage point.',
    'upright3': 'Sacrifice: The Hanged Man represents sacrifice and selflessness. It suggests the willingness to make personal sacrifices or endure temporary discomfort for the sake of greater growth or spiritual understanding.',
    'upright4': 'Perspective Shift: This card symbolizes a shift in perspective or a change in how you perceives the world. The Hanged Man signifies the need to look at things from a different angle, challenge conventional thinking, and embrace alternative viewpoints.',
    'upright5': 'Enlightenment: The Hanged Man upright signifies the potential for spiritual enlightenment and profound wisdom. It represents a transformative journey of self-discovery and inner illumination, gained through surrender and open-mindedness.',
    'reversed1': 'Resistance: The Hanged Man reversed suggests resistance to change or a reluctance to let go. It represents a stubbornness or unwillingness to embrace new perspectives or release attachments that may be hindering personal growth.',
    'reversed2': 'Stagnation: This card signifies a state of stagnation or being stuck. The Hanged Man reversed represents a lack of progress or movement, often due to resistance or fear of stepping out of your comfort zone.',
    'reversed3': 'Lack of Surrender: In the reversed position, the Hanged Man suggests a resistance to surrendering or letting go of control. It signifies a struggle to release control and trust in the natural flow of life, resulting in a sense of being trapped or restricted.',
    'reversed4': 'Narrow Perspective: The Hanged Man reversed symbolizes a limited or narrow perspective. It represents an inability or unwillingness to see alternative viewpoints or consider different possibilities, which may hinder personal growth and understanding.',
    'reversed5': 'Delayed Enlightenment: This card suggests a delay in achieving spiritual enlightenment or gaining deeper insights. The Hanged Man reversed signifies obstacles or internal resistance that prevent the individual from experiencing the transformative journey associated with this card in its upright position.',
    'img': '',
  },
  'death': {
    'cardName': 'Death',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '13',
    'romanCardNum': 'XIII',
    'description': 'The Death card unveils the profound cycle of transformation, where old patterns crumble to make way for rebirth. A skeletal figure, wielding a scythe, represents the inevitability of change. Death is not an end, but a powerful force of regeneration. It invites us to release attachments, surrender to the natural cycles of life, and embrace the transformative power of letting go. Through the death of the old, we transcend limitations, discover inner strength, and emerge anew. Embrace the transformative embrace of Death, for it heralds the birth of limitless possibilities.',    
    'upright1': 'Step into the realm of Death, where endings give birth to new beginnings. Cloaked in black, Death emerges as a catalyst for transformation. A scythe in hand, he cuts through the old, paving the way for rebirth. The withered sun on the horizon symbolizes the completion of a cycle. In the realm of Death, release what no longer serves you, surrender to the inevitable cycles of life, and embrace the beauty of impermanence. From the ashes of the old, a phoenix rises, promising renewal and profound metamorphosis.',
    'upright2': 'Rebirth: This card embodies rebirth and renewal. The Death card signifies the shedding of old patterns, beliefs, or relationships, allowing for a fresh start and the opportunity to embrace new possibilities.',
    'upright3': 'Transition: The Death card symbolizes a transition or passage from one state to another. It represents a period of significant transition and adjustment, often accompanied by inner reflection and personal growth.',
    'upright4': 'Letting Go: This card signifies the need to let go of attachments or aspects of life that no longer serve a purpose. The Death upright suggests releasing what is no longer needed to create space for new experiences and opportunities.',
    'upright5': 'Liberation: The Death card represents liberation and liberation from the past or self-imposed limitations. It signifies breaking free from old patterns, habits, or beliefs that have held you back, leading to a sense of freedom and empowerment.',
    'reversed1': 'Resistance to Change: The Death reversed suggests a resistance to change or an unwillingness to let go of old patterns or situations. It represents a fear of transformation and a clinging to familiar but stagnant circumstances.',
    'reversed2': 'Stagnation: This card signifies a state of stagnation or being stuck in a phase of life. The Death reversed represents a lack of growth or progress due to an aversion to necessary changes or an inability to move forward.',
    'reversed3': 'Fear of Endings: In the reversed position, the Death card symbolizes a fear of endings or a reluctance to embrace necessary closures. It suggests holding onto situations or relationships that have reached your natural end, resulting in an inability to move into new phases of life.',
    'reversed4': 'Resisting Transformation: The Death reversed represents resisting personal transformation or avoiding the necessary inner work. It signifies a reluctance to let go of old identities, beliefs, or behaviors that are preventing growth and evolution.',
    'reversed5': 'Delayed Rebirth: This card suggests a delay in experiencing the transformative rebirth associated with the Death card in its upright position. The Death reversed signifies being stuck in a state of limbo or resisting the necessary changes that would lead to personal renewal and growth.',
    'img': '',
  },

  'temperance': {
    'cardName': 'Temperance',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '14',
    'romanCardNum': 'XIV',
    'description': 'The Temperance card invites you to dance with harmony and find balance amidst the ebb and flow of life. An angel gracefully pours liquid between two vessels, blending opposing forces. It symbolizes the alchemical union of fire and water, spirit and matter. In the realm of Temperance, patience and moderation prevail, guiding you towards inner healing and integration. Embrace the art of blending, harmonizing your inner elements, and discovering the power of equilibrium. Through temperance, you unlock the transformative magic that brings serenity and wholeness to your journey.',
    'upright1': 'Balance: The Temperance upright represents finding balance and harmony in all aspects of life. It signifies the need for moderation, patience, and integration, allowing for a smooth flow of energies and experiences.',
    'upright2': 'Healing: This card embodies healing and restoration. The Temperance card suggests the need to find inner peace and emotional healing by blending opposing forces and finding equilibrium.',
    'upright3': 'Adaptability: The Temperance card signifies adaptability and flexibility. It represents the ability to navigate through life\'s challenges with grace and resilience, adjusting to changing circumstances while maintaining inner stability.',
    'upright4': 'Divine Guidance: This card symbolizes divine guidance and spiritual support. The Temperance upright suggests connecting with higher wisdom or seeking guidance from spiritual sources to navigate life\'s ups and downs.',
    'upright5': 'Moderation: The Temperance card represents moderation in all things. It encourages finding a middle ground and avoiding extremes, fostering a balanced approach to life\'s pleasures and responsibilities.',
    'reversed1': 'Imbalance: The Temperance reversed suggests a lack of balance or harmony. It represents a difficulty in finding moderation and integration, leading to extremes or instability in various areas of life.',
    'reversed2': 'Impatience: This card signifies impatience and a lack of tolerance. The Temperance reversed suggests a tendency to rush or seek quick fixes, disregarding the need for patience and gradual progress.',
    'reversed3': 'Disharmony: In the reversed position, the Temperance card represents disharmony or conflicts. It signifies difficulties in finding common ground or reconciling opposing forces, resulting in tension or discord.',
    'reversed4': 'Excess: This card symbolizes excessiveness or overindulgence. The Temperance reversed suggests a lack of self-control or an imbalance in your desires, leading to overconsumption or addictive behaviors.',
    'reversed5': 'Lack of Adaptability: The Temperance reversed signifies a resistance to change or an inability to adapt to new circumstances. It suggests a rigid mindset or an aversion to embracing different perspectives, hindering personal growth and adaptability.',
    'img': '',
  },


  'the devil': {
    'cardName': 'The Devil',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '15',
    'romanCardNum': 'XV',
    'description': 'The Devil card captivates with seductive allure, tempting souls into the depths of their desires. Bound by chains of materialism and unhealthy attachments, it exposes the illusions that enslave us. The Devil challenges us to confront our shadows, to break free from self-imposed limitations, and reclaim our personal power. Through awareness and liberation, we can transcend the seductive grip of temptation and embrace our true selves. The Devil reminds us that true freedom lies in acknowledging and releasing the chains that bind us, leading to a path of authentic transformation.',
    'upright1': 'Temptation: The Devil upright represents temptation and seduction. It signifies the allure of material desires, unhealthy attachments, or addictive behaviors that may lead you astray.',
    'upright2': 'Bondage: This card embodies bondage or being trapped in unhealthy patterns or relationships. The Devil upright signifies the need to break free from self-imposed limitations or destructive influences that keep you bound.',
    'upright3': 'Shadow Self: The Devil card symbolizes the shadow self and the darker aspects of human nature. It represents confronting and integrating your inner demons, fears, and unresolved issues for personal growth and transformation.',
    'upright4': 'Materialism: This card signifies excessive materialism and a focus on material possessions or external gratification. The Devil upright warns against becoming overly attached to worldly desires or prioritizing material gain above spiritual or emotional well-being.',
    'upright5': 'Self-Destruction: The Devil upright suggests the potential for self-destructive behavior or self-sabotage. It serves as a warning to be mindful of your actions and choices to avoid detrimental consequences and negative outcomes.',
    'reversed1': 'Liberation: The Devil reversed represents liberation from bondage or unhealthy attachments. It signifies breaking free from destructive patterns, releasing yourself from the influence of negative forces, and reclaiming personal power.',
    'reversed2': 'Release: This card embodies release and letting go of self-imposed limitations or harmful influences. The Devil reversed suggests shedding the chains of unhealthy habits, beliefs, or relationships to embrace a path of freedom and self-discovery.',
    'reversed3': 'Overcoming Temptation: The Devil reversed symbolizes overcoming temptation and resisting negative influences. It signifies the strength to resist the allure of harmful behaviors or desires that may lead you astray from your true path.',
    'reversed4': 'Personal Empowerment: This card signifies personal empowerment and taking control of your life. The Devil reversed suggests reclaiming personal sovereignty, making conscious choices, and aligning with your values and authentic self.',
    'reversed5': 'Breaking Cycles: The Devil reversed represents the opportunity to break free from repetitive patterns or cycles of self-destructive behavior. It signifies a chance to break away from negative habits, thoughts, or relationships that hinder personal growth and progress.',
    'img': '',
  },

  'the tower': {
    'cardName': 'The Tower',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '16',
    'romanCardNum': 'XVI',
    'description': 'The Tower card strikes with disruptive force, shattering foundations and challenging the status quo. Lightning cracks across the sky, demolishing what once stood firm. From chaos arises the opportunity for rebirth and growth. The Tower symbolizes the collapse of illusions, prompting a necessary awakening. Embrace the upheaval, for within the wreckage lies the potential for profound transformation. Release attachments, surrender to the divine disruption, and with courage and resilience, rebuild anew. In the destruction of the Tower, a phoenix rises, symbolizing the potential for renewal and the triumph over adversity.',
    'upright1': 'Sudden Upheaval: The Tower upright represents sudden and dramatic upheaval or disruption. It signifies a major shake-up or unexpected event that shatters existing structures and routines, challenging the status quo.',
    'upright2': 'Destruction: This card embodies destruction and the dismantling of old systems, beliefs, or relationships. The Tower upright signifies the need to tear down what no longer serves a purpose to make way for new beginnings and growth.',
    'upright3': 'Liberation: The Tower upright symbolizes liberation and breaking free from confining circumstances or limiting beliefs. It represents an opportunity for personal liberation, allowing you to shed old patterns and embrace a more authentic path.',
    'upright4': 'Awakening: This card signifies an awakening or realization triggered by a significant event. The Tower upright represents a moment of profound insight or revelation that leads to a new understanding of yourself or the world.',
    'upright5': 'Divine Intervention: The Tower upright suggests the intervention of higher forces or divine intervention in your life. It represents a transformative experience that is ultimately for the greater good, even if it may initially feel chaotic or disruptive.',
    'reversed1': 'Avoidance: The Tower reversed signifies a tendency to avoid or suppress necessary changes or upheavals in your life. It suggests a reluctance to confront or address underlying issues, which can lead to a buildup of tension or explosive situations.',
    'reversed2': 'Temporary Stability: This card represents temporary stability or the illusion of security. The Tower reversed suggests a false sense of security or the delay of inevitable change, creating a potential for a more significant and unexpected disruption in the future.',
    'reversed3': 'Resistance to Transformation: In the reversed position, the Tower signifies a resistance to personal transformation or a fear of the unknown. It suggests a reluctance to let go of outdated structures or belief systems, hindering personal growth and evolution.',
    'reversed4': 'Release of Repressed Emotions: The Tower reversed can represent the release of repressed emotions or suppressed energies. It signifies a breaking down of emotional barriers or past traumas, leading to an eventual catharsis or emotional release.',
    'reversed5': 'Gradual Change: This card suggests a slower or more gradual process of change or upheaval. The Tower reversed signifies a gentler transformation, where shifts occur over time rather than in a sudden and dramatic manner as seen in the upright position of the card.',
    'img': '',
  },

  'the star': {
    'cardName': 'The Star',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '17',
    'romanCardNum': 'XVII',
    'description': 'The Star card invites you to gaze upon the celestial canvas where dreams take flight. A radiant star shines with a luminous glow, casting hope and inspiration upon a serene landscape. It symbolizes healing, guidance, and serendipitous blessings. In the realm of the Star, infinite possibilities unfold, rejuvenating your spirit and igniting a sense of purpose. Embrace the guiding light of your aspirations, for even in the darkest of nights, the Star reminds you to trust in the magic of the universe and believe in the power of your own inner brilliance.',
    'uprightKeyword1': 'Hope',
    'uprightKeyword2':'Inspiration',
    'upright1': 'Hope: The Star upright represents hope and optimism. It signifies a sense of faith in the future, even in the midst of challenges or difficult times. It symbolizes a guiding light that brings reassurance and inspires confidence.',
    'upright2': 'Inspiration: This card embodies inspiration and creative energy. The Star signifies a connection to your inner guidance and intuition, leading to inspired ideas, visions, and a renewed sense of purpose.',
    'upright3': 'Healing: The Star card represents healing and restoration. It signifies a period of emotional, spiritual, or physical healing, bringing about a sense of renewal and rejuvenation. It symbolizes the presence of divine healing energies.',
    'upright4': 'Guidance: The Star upright signifies guidance and divine assistance. It represents a connection to higher wisdom, spiritual guidance, or supportive influences that provide direction and illuminate the path ahead.',
    'upright5': 'Faith: This card embodies faith and trust in the universe. The Star represents the belief that everything happens for a reason and that there is a greater plan unfolding. It encourages having faith in yourself and the journey, knowing that you are being guided and supported.',
    'reversed1': 'Disillusionment: The Star reversed suggests a sense of disillusionment or loss of faith. It signifies a period of doubt or disappointment, where you may feel disconnected from your inner guidance or struggle to find hope and inspiration.',
    'reversed2': 'Lack of Direction: This card represents a lack of clarity or direction. The Star reversed signifies feeling lost or uncertain about the path ahead, lacking a clear vision or purpose. It may indicate a need for inner reflection and reevaluation.',
    'reversed3': 'Pessimism: The Star reversed can symbolize pessimism or a negative outlook. It suggests a tendency to focus on limitations or setbacks, losing sight of the positive aspects of life. It encourages shifting perspective and finding ways to cultivate optimism.',
    'reversed4': 'Blocked Intuition: In the reversed position, the Star signifies a disconnection from your intuition or inner guidance. It suggests difficulty accessing and trusting your intuition, resulting in a sense of confusion or being out of touch with your true self.',
    'reversed5': 'Healing Delayed: This card represents a delay in healing or the resolution of emotional or spiritual wounds. The Star reversed suggests that the process of healing may be slower or require additional effort. It encourages patience and perseverance in the journey toward inner wholeness.',
    'img': '',
  },
  'the moon': {
    'cardName': 'The Moon',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '18',
    'romanCardNum': 'XVIII',
    'description': 'The Moon card beckons you into a mysterious realm where shadows dance and secrets stir. Moonlight shimmers upon a tranquil lake, revealing hidden truths. Illusions weave their enchantment, calling for intuition and deep reflection. In this enigmatic landscape, emotions surge, dreams emerge, and the subconscious speaks. The Moon whispers of the power of the unknown and the need to trust your instincts. Embrace the Moon\'s mystical embrace, navigate the labyrinth of your inner world, and discover profound insights that lead to transformation and spiritual illumination.',
    'upright1': 'Intuition: The Moon upright represents intuition and the subconscious mind. It signifies a deep connection to your inner wisdom and the ability to trust your instincts and intuition in navigating through uncertainties.',
    'upright2': 'Mystery: This card embodies mystery and the hidden aspects of life. The Moon signifies the exploration of the unknown, inviting you to embrace the mysteries of existence and delve into the depths of the unconscious.',
    'upright3': 'Reflection: The Moon card symbolizes reflection and introspection. It encourages taking the time to look within, explore your emotions, and gain deeper self-understanding. It represents a period of inner reflection and self-discovery.',
    'upright4': 'Illusion: The Moon upright signifies illusions and deceptive appearances. It suggests the need to look beyond surface-level realities and explore the hidden truths. It reminds you to be aware of illusions and to trust your intuition to discern what is real.',
    'upright5': 'Dreams: This card represents dreams, both literal and metaphorical. The Moon signifies the realm of dreams, imagination, and the subconscious. It encourages paying attention to dreams, symbols, and messages from the unconscious mind for guidance and insight.',
    'reversed1': 'Deception: The Moon reversed suggests deception or illusions. It signifies a time of confusion or being misled by appearances. It warns against relying solely on intuition or gut feelings without discernment.',
    'reversed2': 'Emotional Turmoil: This card represents emotional turmoil or instability. The Moon reversed suggests that emotions may be overwhelming or difficult to understand, leading to inner confusion or inner conflicts. It indicates the need for emotional grounding and stability.',
    'reversed3': 'Unconscious Blockages: The Moon reversed signifies blocked or suppressed emotions and subconscious issues. It suggests that unresolved emotional patterns or hidden fears may be surfacing, creating obstacles to personal growth and self-awareness.',
    'reversed4': 'Release of Fears: In the reversed position, the Moon represents an opportunity to release fears and face inner demons. It symbolizes a time of confronting deep-seated fears and anxieties, allowing for healing and personal transformation.',
    'reversed5': 'Lack of Clarity: The Moon reversed signifies a lack of clarity or understanding. It suggests that the path forward may be unclear or that important information is being obscured. It calls for patience and discernment to navigate through uncertainties and seek clarity.',
    'img': '',
  },
  'the sun': {
    'cardName': 'The Sun',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '19',
    'romanCardNum': 'XIX',
    'description': 'The Sun card radiates pure joy and vitality, illuminating the world with its golden light. Nature flourishes under its warm embrace, and laughter fills the air. It represents a time of abundance, happiness, and success. The Sun\'s energy invigorates and empowers, reminding us to embrace our inner light and shine brightly. Like a beacon of positivity, it inspires optimism and encourages us to embrace life\'s blessings with gratitude. The Sun card reminds us that even in the darkest moments, the sun will rise again, bringing warmth, growth, and renewed hope.',
    'upright1': 'Joy: The Sun upright represents joy, happiness, and positivity. It signifies a period of celebration, vitality, and a sense of inner radiance.',
    'upright2': 'Vitality: This card embodies vitality and energy. The Sun signifies a renewed sense of vigor, vitality, and enthusiasm for life. It represents a time of increased vitality and well-being.',
    'upright3': 'Success: The Sun card symbolizes success, accomplishment, and achievement. It signifies the realization of goals and aspirations, bringing about a sense of fulfillment and satisfaction.',
    'upright4': 'Clarity: The Sun upright represents clarity and illumination. It signifies a time of clear vision, understanding, and insight. It represents a period of heightened awareness and a strong sense of purpose.',
    'upright5': 'Optimism: This card embodies optimism and a positive outlook. The Sun signifies a bright and hopeful future, encouraging you to embrace optimism, positivity, and a belief in the abundance of life.',
    'reversed1': 'Temporary setbacks: The Sun reversed suggests temporary setbacks or obstacles on the path to success. It signifies challenges or delays that may hinder the attainment of goals or impede progress.',
    'reversed2': 'Lack of clarity: In the reversed position, the Sun signifies a lack of clarity or understanding. It suggests a period of confusion or uncertainty, where you may struggle to find your direction or purpose.',
    'reversed3': 'Dimmed enthusiasm: The Sun reversed represents a decrease in enthusiasm or a loss of vitality. It may indicate a temporary decrease in energy levels or a feeling of being drained or uninspired.',
    'reversed4': 'Disconnection from joy: This card signifies a disconnection from joy or a struggle to find happiness. The Sun reversed suggests a need to reconnect with your inner light and find ways to cultivate joy and positivity.',
    'reversed5': 'Overconfidence: In the reversed position, the Sun can indicate overconfidence. It warns against becoming overly self-centered or arrogant, reminding you to stay grounded and humble in your achievements.',
    'img': '',
  },
  'judgement': {
    'cardName': 'Judgement',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '20',
    'romanCardNum': 'XX',
    'description': 'The Judgment card heralds a transformative awakening, where souls rise from the depths of their past. The angel\'s trumpet calls for self-reflection and spiritual rebirth. It symbolizes a time of reckoning and embracing our true purpose. With clarity and courage, we release judgment and invite redemption. The Judgment card invites us to listen to our inner voice, embrace personal growth, and step into a new chapter of our lives. It signals the moment of divine judgment, where we are guided towards liberation and the fulfillment of our higher calling.',
    'upright1': 'Rebirth: The Judgment card upright represents a period of rebirth or spiritual awakening. It signifies a time of personal transformation, renewal, and stepping into a higher level of consciousness.',
    'upright2': 'Reflection: This card embodies reflection and self-evaluation. The Judgment card signifies a call to reflect on your past actions, decisions, and choices, and to assess how they have shaped your present circumstances.',
    'upright3': 'Redemption: The Judgment card symbolizes redemption and forgiveness. It signifies a chance for healing and making amends, both with oneself and with others. It represents a time of reconciliation and letting go of past regrets or resentments.',
    'upright4': 'Revelation: The Judgment card represents a revelation or deep inner knowing. It signifies gaining clarity and understanding, seeing things from a broader perspective, and receiving divine insights or guidance.',
    'upright5': 'Transformation: This card embodies transformation and the awakening of higher potentials. The Judgment card signifies a profound shift in consciousness, leading to personal growth, self-realization, and embracing your true calling or purpose.',
    'reversed1': 'Self-judgment: The Judgment card reversed suggests self-judgment or being overly critical of oneself. It signifies a tendency to hold onto guilt, shame, or past mistakes, hindering personal growth and acceptance.',
    'reversed2': 'Resistance to change: In the reversed position, the Judgment card represents resistance to change or a reluctance to confront necessary transformations. It suggests a fear of stepping into the unknown and a hesitation to embrace new opportunities or paths.',
    'reversed3': 'Ignoring inner calling: The Judgment card reversed signifies ignoring or neglecting your inner calling or intuitive guidance. It suggests a disconnection from your true purpose or a refusal to listen to the deeper wisdom within.',
    'reversed4': 'Lack of self-reflection: This card represents a lack of self-reflection or an avoidance of introspection. The Judgment reversed suggests a tendency to avoid taking responsibility for your actions or to overlook the lessons and insights gained from past experiences.',
    'reversed5': 'Delayed spiritual growth: In the reversed position, the Judgment card indicates a delay in spiritual growth or a resistance to spiritual awakening. It suggests a missed opportunity for personal transformation or a reluctance to embrace spiritual truths and lessons.',
    'img': '',
  },
   'the world': {
    'cardName': 'The World',
    'type': 'Major Arcana',
    'suit': '',
    'cardNum': '21',
    'romanCardNum': 'XXI',
    'description': 'The World card unveils the culmination of a grand journey, where completion and fulfillment await. It represents unity and wholeness, as all elements converge harmoniously. A dancer gracefully floats at the center, symbolizing harmony and balance. The World signifies the attainment of goals, expansion of consciousness, and the integration of diverse experiences. It invites celebration and acknowledges the interconnectedness of all things. In this card, we recognize that we are part of a vast cosmic tapestry, and through understanding our place, we embrace the infinite possibilities that lie before us.',
    'upright1': 'Completion: The World card upright represents completion and fulfillment. It signifies the successful culmination of a journey or project, indicating a sense of achievement, integration, and wholeness.',
    'upright2': 'Wholeness: This card embodies wholeness and unity. The World signifies a harmonious balance of all aspects of oneself and the surrounding world. It represents a state of inner harmony and alignment.',
    'upright3': 'Expansion: The World card symbolizes expansion and embracing new possibilities. It signifies a time of growth, exploration, and embracing a broader perspective. It represents the opening of doors and new horizons.',
    'upright4': 'Integration: This card signifies integration and synthesis. The World card represents the blending and harmonization of different aspects of life, bringing together diverse experiences, knowledge, and wisdom into a cohesive whole.',
    'upright5': 'Success and fulfillment: The World upright represents success, fulfillment, and the realization of goals or dreams. It signifies a time of celebration and a sense of accomplishment. It represents the recognition of your worth and the rewards of hard work.',
    'reversed1': 'Incompletion: The World card reversed suggests a sense of incompletion or unfinished business. It signifies that there may be loose ends or unresolved matters that require attention before achieving a true sense of closure.',
    'reversed2': 'Disconnection: In the reversed position, the World card represents a disconnection or lack of harmony. It suggests a feeling of being out of sync or out of touch with oneself or the world, resulting in a sense of imbalance or dissatisfaction.',
    'reversed3': 'Resistance to change: The World reversed signifies resistance to change or a reluctance to embrace new opportunities and experiences. It suggests a fear of stepping out of your comfort zone or clinging to familiar patterns, hindering personal growth.',
    'reversed4': 'Delayed fulfillment: This card represents a delay in experiencing fulfillment or achieving goals. The World reversed suggests that external or internal factors may be impeding progress, requiring patience and perseverance to overcome obstacles.',
    'reversed5': 'Lack of integration: In the reversed position, the World card symbolizes a lack of integration or difficulty in finding harmony within oneself and the surrounding world. It suggests the need for inner reflection and a willingness to address internal conflicts or contradictions.',
    'img': '',
  },
  //  '': {
  //   'type': '',
  //   'suit': '',
  //   'cardName': '',
  //   'description': '',
  //   'upright1': '',
  //   'upright2': '',
  //   'upright3': '',
  //   'upright4': '',
  //   'upright5': '',
  //   'reversed1': '',
  //   'reversed2': '',
  //   'reversed3': '',
  //   'reversed4': '',
  //   'reversed5': '',
  //   'img': '',
  // },
  //  '': {
  //   'type': '',
  //   'suit': '',
  //   'cardName': '',
  //   'description': '',
  //   'upright1': '',
  //   'upright2': '',
  //   'upright3': '',
  //   'upright4': '',
  //   'upright5': '',
  //   'reversed1': '',
  //   'reversed2': '',
  //   'reversed3': '',
  //   'reversed4': '',
  //   'reversed5': '',
  //   'img': '',
  // },
  //  '': {
  //   'type': '',
  //   'suit': '',
  //   'cardName': '',
  //   'description': '',
  //   'upright1': '',
  //   'upright2': '',
  //   'upright3': '',
  //   'upright4': '',
  //   'upright5': '',
  //   'reversed1': '',
  //   'reversed2': '',
  //   'reversed3': '',
  //   'reversed4': '',
  //   'reversed5': '',
  //   'img': '',
  // },
  //  '': {
  //   'type': '',
  //   'suit': '',
  //   'cardName': '',
  //   'description': '',
  //   'upright1': '',
  //   'upright2': '',
  //   'upright3': '',
  //   'upright4': '',
  //   'upright5': '',
  //   'reversed1': '',
  //   'reversed2': '',
  //   'reversed3': '',
  //   'reversed4': '',
  //   'reversed5': '',
  //   'img': '',
  },
  // '': {
  //   'type': '',
  //   'suit': '',
  //   'cardName': '',
  //   'description': '',
  //   'upright1': '',
  //   'upright2': '',
  //   'upright3': '',
  //   'upright4': '',
  //   'upright5': '',
  //   'reversed1': '',
  //   'reversed2': '',
  //   'reversed3': '',
  //   'reversed4': '',
  //   'reversed5': '',
  //   'img': '',
  // },
  'unknown': {
    'type': 'unknown',
    'cardName': 'unknown',
    'uprightKeywords': 'unknown',
    'reversedKeywords': 'unknown',
    'description': 'unknown',
    'img': 'unknown',
  }  
}

app.get('/', (req,res)=>{
  res.sendFile(__dirname + '/index.html')
})

app.get('/api/:name', (req,res)=>{
  const tarotCards = req.params.name.toLowerCase()
  if(card[tarotCards]){
    res.json(card[tarotCards])
  }else{
    res.json(card['unknown'])
  }
})

app.listen(process.env.PORT || PORT, ()=>{
  console.log(`Woo port ${PORT} is up and running - go catch it!`)
})



