const express = require('express')
const app = express()
const cors = require('cors')
const PORT = 8000

app.use(cors())


const card = {
  'the fool': {
    'type': 'Major Arcana',
    'cardName': 'The Fool',
    'description': 'Behold the Fool, a daring adventurer at the precipice of destiny. With carefree abandon, he stands on the edge, ready to leap into the unknown. Unaware of the imminent plunge, his gaze fixates on the boundless sky. Clutching a humble knapsack, he embraces minimalism and unlimited potential. A white rose embodies his purity, while a loyal canine companion nudges him forward. The looming mountains foretell challenges, yet his unyielding spirit fuels his expedition. With fearless steps, he embarks on a transformative journey, leaving behind the constraints of fear and embracing the magic of the Fool\'s quest.',
    'uprightKeywords': 'Spontaneity &#x2022; Innocence &#x2022; Optimism &#x2022; Freedom &#x2022; Beginnings',
    'upright1': 'Spontaneity: The Fool upright represents a carefree and spontaneous nature. It is associated with taking risks and embracing new adventures without fear or hesitation.',
    'upright2': 'Innocence: The Fool embodies a sense of childlike innocence and naivety. It suggests a lack of preconceived notions or biases, allowing for a fresh perspective and open-mindedness.',
    'upright3': 'Optimism: This card radiates positivity and optimism. The Fool upright encourages a hopeful outlook on life, emphasizing the belief that everything will work out for the best.',
    'upright4': 'Freedom: The Fool symbolizes freedom from constraints and limitations. It signifies a willingness to break free from societal norms or expectations, embracing personal freedom and individuality.',
    'upright5': 'Beginnings: The Fool is associated with new beginnings and fresh starts. It represents the start of a journey or a new phase in life, urging you to embrace change and take the first steps towards your goals.',
    'reversed1': 'Recklessness: The Fool reversed indicates a lack of caution or thoughtfulness in your actions. It suggests impulsive behavior and a tendency to act without considering the consequences.',
    'reversed2': 'Foolishness: In the reversed position, the Fool represents poor judgment or decision-making. It signifies a lack of wisdom or understanding, leading to unwise choices or actions.',
    'reversed3': 'Naivety: The Fool reversed suggests a state of being overly trusting or gullible. It signifies a vulnerability to deception or manipulation, as well as a tendency to overlook important details or warning signs.',
    'reversed4': 'Stagnation: This card in reverse can indicate a resistance to change or a fear of taking risks. It suggests a reluctance to embrace new opportunities or step out of your comfort zone, leading to a sense of stagnation or missed chances.',
    'reversed5': 'Consequences: The Fool reversed often signifies facing the consequences of your actions or decisions. It warns of potential setbacks, misunderstandings, or negative outcomes resulting from hasty or ill-considered choices.',
    'img': '/img/the-fool.png',
  },
  'the magician': {
    'type': 'Major Arcana',
    'cardName': 'The Magician',
    'description': 'Witness the Magician, a master of infinite possibilities and conjurer of destiny. With arms outstretched, he bridges the realms of spirit and matter. His touch transforms energy into tangible realities, a conduit of creation. Clad in a robe of purest white, he embodies purity, while his fiery cloak reflects worldly wisdom. Before him, the Tarot symbols await, embodying the elements and his mastery. The infinity symbol above signifies boundless potential, while a self-consuming snake whispers secrets of endless transformation. Amidst blossoming foliage, his visions manifest, a mesmerizing dance of dreams turned into tangible truths.',
    'upright1': 'Mastery: The Magician upright represents a mastery of skills and abilities. It signifies having the knowledge, expertise, and confidence to manifest your desires and goals effectively.',
    'upright2': 'Creativity: This card symbolizes creative energy and the power of imagination. The Magician encourages innovative thinking and resourcefulness in finding unique solutions to challenges.',
    'upright3': 'Manifestation: The Magician upright embodies the ability to manifest your intentions into reality. It signifies the power of focused intention, willpower, and taking action to bring about desired outcomes.',
    'upright4': 'Transformation: The Magician represents a transformative energy that facilitates personal growth and positive change. It suggests harnessing your inner potential and embracing opportunities for self-improvement.',
    'upright5': 'Alignment: This card signifies the alignment of mind, body, and spirit. The Magician upright encourages individuals to tap into your inner wisdom and connect with your higher selves, creating a harmonious balance within yourself and your surroundings.',
    'reversed1': 'Manipulation: The Magician reversed can indicate a tendency towards manipulation or deceit. It suggests the misuse of power or skills for personal gain, leading to dishonesty or trickery.',
    'reversed2': 'Lack of Focus: In the reversed position, the Magician represents a lack of focus or direction. It suggests scattered energy and an inability to harness your abilities effectively, resulting in a lack of progress or achievement.',
    'reversed3': 'Misuse of Power: This card signifies the misuse or abuse of power. It suggests that you may be using your skills or influence in a negative or harmful way, potentially causing harm to others or themselves.',
    'reversed4': 'Ineffectiveness: The Magician reversed represents a lack of effectiveness or inefficiency in your actions. It suggests that despite having the necessary skills or resources, you are unable to utilize them effectively, leading to unsuccessful outcomes or missed opportunities.',
    'reversed5': 'Blocked Potential: This card in reverse can indicate a blockage or suppression of your potential. It suggests a failure to tap into your true abilities or talents, resulting in a sense of stagnation or unfulfilled potential.',
    'img': '',
  },
  'the high priestess': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The High Priestess',
    'description': 'Unveiling the High Priestess, an enchanting guardian of ancient wisdom. Clad in mystic allure, she sits before a veil embellished with tempting pomegranates, concealing the realms of the seen and unseen. Only the bold and initiated may pierce its ethereal barrier. Amidst two majestic pillars, one shrouded in darkness, the other bathed in light, she whispers of profound duality. Surrender to her beckoning embrace, and traverse the hallowed depths where secrets of the universe dance, awaiting those who seek divine revelation.',
    'upright1': 'Intuition: The High Priestess upright represents deep intuition and inner wisdom. It suggests the ability to tap into your subconscious mind and access intuitive insights and knowledge.',
    'upright2': 'Mystery: This card embodies a sense of mystery and hidden knowledge. The High Priestess signifies the presence of secrets, hidden truths, and esoteric wisdom that may be revealed over time.',
    'upright3': 'Feminine Energy: The High Priestess is associated with feminine energy and the divine feminine. It represents intuition, receptivity, and the nurturing aspects of your nature.',
    'upright4': 'Spiritual Connection: This card symbolizes a strong connection to the spiritual realm. It suggests a deep understanding of spiritual matters, meditation, and inner reflection to gain spiritual insights and guidance.',
    'upright5': 'Inner Balance: The High Priestess upright signifies inner balance and harmony. It suggests a state of equilibrium between the conscious and subconscious mind, embracing both rationality and intuition in decision-making and life choices.',
    'reversed1': 'Blocked Intuition: The High Priestess reversed suggests a blockage or suppression of your intuition. It indicates a lack of trust in your inner wisdom and an inability to access or heed intuitive guidance.',
    'reversed2': 'Hidden Knowledge: In the reversed position, the High Priestess represents hidden or obscured knowledge that remains out of reach. It suggests a difficulty in uncovering deeper truths or accessing esoteric wisdom.',
    'reversed3': 'Lack of Understanding: This card signifies a lack of understanding or confusion. The High Priestess reversed suggests a struggle to grasp the deeper meaning or significance of certain experiences or situations.',
    'reversed4': 'Disconnection from Spirituality: In the reversed position, the High Priestess indicates a disconnection from spirituality or a lack of spiritual exploration. It suggests a diminished connection to your higher self and a disregard for inner reflection or spiritual practices.',
    'reversed5': 'Imbalance: The High Priestess reversed suggests an imbalance between the conscious and subconscious mind. It signifies a lack of inner harmony, where rationality and intuition are at odds, leading to confusion or indecisiveness.',
    'img': '',
  },
  'the empress': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The Empress',
    'description': 'Enter the realm of the Empress, a radiant force of creation and nurturing abundance. Adorned in lush greenery, she sits upon a throne of blossoming beauty. The embodiment of fertility, she nurtures life\'s bountiful harvest. Golden wheat fields sway in homage to her abundant grace. Her loving gaze and compassionate embrace radiate maternal power. With each breath, she breathes life into dreams and manifests them into reality. The Empress, a goddess of earthly delights, invites you to embrace your creative potential and immerse yourself in the abundant tapestry of existence.',
    'upright1': 'Fertility: The Empress upright represents fertility, both in terms of physical fertility and the ability to nurture and create. It signifies a time of abundance, growth, and the potential for new beginnings.',
    'upright2': 'Nurturing: This card embodies nurturing and maternal energy. The Empress signifies a caring and compassionate nature, offering support and guidance to others. It represents the ability to create a loving and nurturing environment.',
    'upright3': 'Creativity: The Empress upright symbolizes creativity and artistic expression. It suggests a time of inspiration and the birth of new ideas. This card encourages embracing your creative abilities and exploring artistic endeavors.',
    'upright4': 'Abundance: This card represents abundance and prosperity. The Empress signifies a time of material and emotional abundance, where resources and opportunities are readily available. It suggests a sense of wealth and fulfillment.',
    'upright5': 'Harmony: The Empress upright signifies harmony and balance. It represents a state of equilibrium and contentment, where you feels connected to the natural rhythms of life. This card suggests finding harmony within yourself and in relationships with others.',
    'reversed1': 'Lack of Nurturing: The Empress reversed suggests a lack of nurturing or neglectful behavior. It signifies a failure to provide care and support to yourself or others. It may indicate difficulties in creating a loving and nurturing environment.',
    'reversed2': 'Creative Block: In the reversed position, the Empress represents a creative block or a struggle to express yourself artistically. It suggests a lack of inspiration or difficulty in manifesting creative ideas.',
    'reversed3': 'Scarcity: This card indicates a sense of scarcity or a lack of abundance. The Empress reversed signifies a period of limited resources, both material and emotional. It may suggest financial challenges or a feeling of emptiness.',
    'reversed4': 'Disharmony: The Empress reversed represents disharmony and imbalance. It suggests a lack of harmony within yourself or in relationships. It may indicate conflicts, discord, or a sense of disconnection from the natural rhythms of life.',
    'reversed5': 'Self-neglect: This card suggests self-neglect or a disregard for self-care. The Empress reversed signifies a tendency to put others\' needs before your own, leading to a depletion of energy and a lack of personal fulfillment.',
    'img': '',
  },
  'the emperor': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The Emperor',
    'description': 'Commanding and resolute, the Emperor rules with unwavering authority. Seated on a throne of strength, his presence exudes power and leadership. Clad in regal armor, he channels the fiery energy of ambition. A long white beard symbolizes wisdom earned through experience. His gaze penetrates, as he forges order from chaos. The ram\'s heads on his throne represent his fierce determination. The Emperor, a master of structure and discipline, implores you to embrace your inner strength and embrace the challenges that lie ahead with unwavering confidence.',
    'upright1': 'Authority: The Emperor upright represents authority and leadership. It symbolizes a strong and confident individual who is capable of taking charge and making decisions with clarity and conviction.',
    'upright2': 'Structure: This card embodies structure and organization. The Emperor signifies the establishment of order and systems, providing a solid foundation for stability and success.',
    'upright3': 'Power: The Emperor upright signifies personal power and control. It represents the ability to assert yourself and influence your surroundings, displaying strength and resilience in the face of challenges.',
    'upright4': 'Discipline: This card represents discipline and self-control. The Emperor signifies the importance of setting boundaries, adhering to rules, and maintaining a focused approach in order to achieve goals.',
    'upright5': 'Responsibility: The Emperor upright embodies responsibility and accountability. It signifies taking on leadership roles, fulfilling obligations, and being accountable for your actions and decisions. This card emphasizes the need for wise and responsible governance.',
    'reversed1': 'Authoritarianism: The Emperor reversed suggests a misuse or abuse of authority. It signifies a tendency towards oppressive or dictatorial behavior, where power is exercised in a domineering or controlling manner.',
    'reversed2': 'Lack of Structure: In the reversed position, the Emperor represents a lack of structure or disorganization. It signifies a difficulty in establishing and maintaining order, leading to chaos or instability.',
    'reversed3': 'Power Struggles: This card suggests power struggles or challenges to authority. The Emperor reversed signifies conflicts or resistance to established leadership, often resulting from a lack of trust or dissatisfaction with the current structure.',
    'reversed4': 'Lack of Discipline: In the reversed position, the Emperor signifies a lack of discipline or self-control. It suggests a tendency towards impulsiveness or erratic behavior, leading to a lack of focus or direction.',
    'reversed5': 'Irresponsibility: The Emperor reversed embodies a lack of responsibility or accountability. It suggests an avoidance of leadership roles or a failure to fulfill obligations and duties. This card highlights a lack of maturity or unwillingness to take on necessary responsibilities.',
    'img': '',
  },
  'the hierophant': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The Hierophant',
    'description': 'Enter the realm of the Hierophant, a beacon of spiritual wisdom and divine guidance. Seated on a sacred throne, he embodies the essence of tradition and ritual. Clad in robes adorned with sacred symbols, his presence invokes reverence. The keys at his feet symbolize unlocking hidden knowledge. Two acolytes beside him seek his teachings. The Hierophant, a conduit of ancient wisdom, invites you to embrace tradition while seeking your own spiritual truths. Through his guidance, you\'ll unravel the profound mysteries of existence and find harmony between tradition and personal enlightenment.',
    'upright1': 'Tradition: The Hierophant upright represents tradition and conformity. It signifies adherence to established norms, rituals, and cultural or religious customs.',
    'upright2': 'Spiritual Guidance: This card embodies spiritual guidance and wisdom. The Hierophant signifies the presence of a spiritual teacher or mentor who imparts valuable knowledge and guidance on matters of spirituality and belief systems.',
    'upright3': 'Authority: The Hierophant upright signifies authority and leadership in spiritual or religious matters. It represents an individual or institution with a significant role in providing guidance, interpreting doctrines, or upholding religious teachings.',
    'upright4': 'Conformity: This card suggests a need for conformity or adherence to societal norms. The Hierophant signifies a desire to fit in or seek validation through adhering to established structures and belief systems.',
    'upright5': 'Rituals and Ceremonies: The Hierophant upright embodies rituals, ceremonies, and formalities. It represents the importance of participating in meaningful rituals or ceremonies to foster spiritual connection and growth. This card emphasizes the significance of tradition and shared experiences within a community or group. ',
    'reversed1': 'Nonconformity: The Hierophant reversed signifies a rejection of traditional norms and a resistance to conformity. It suggests a desire to break free from established structures and explore alternative paths or belief systems.',
    'reversed2': 'Unconventional Spirituality: In the reversed position, the Hierophant represents a departure from mainstream spirituality or organized religion. It suggests a personal exploration of spirituality that diverges from established practices or doctrines.',
    'reversed3': 'Questioning Authority: This card suggests a skepticism towards authority figures or institutions. The Hierophant reversed signifies a tendency to question the teachings and guidance of traditional authorities, seeking your own truths and beliefs.',
    'reversed4': 'Unorthodox Practices: The Hierophant reversed embodies unorthodox or alternative practices. It represents a willingness to explore different spiritual paths or unconventional methods of seeking enlightenment or inner wisdom.',
    'reversed5': 'Spirituality in Personal Terms: This card suggests an individualized approach to spirituality. The Hierophant reversed signifies the importance of finding your own spiritual path and defining your beliefs and practices based on personal experiences and insights.',
    'img': '',
  },
  'the lovers': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The Lovers',
    'description': 'Embark on the journey of the Lovers, where passion and harmony entwine. Two souls stand at the precipice of profound connection. Their gazes lock, igniting a flame that transcends the physical. Above, an angel blesses their union, whispering celestial guidance. The intertwined trees symbolize the intertwining of their destinies. Eros\' arrow strikes deep, forging a bond that defies time and space. In the realm of the Lovers, love conquers all, urging you to embrace the transformative power of true connection and celebrate the harmonious dance of hearts entwined.',
    'upright1': 'Love: The Lovers upright represents love in all its forms, including romantic love, deep connections, and harmonious relationships. It signifies a union of hearts and a deep emotional bond.',
    'upright2': 'Partnership: This card embodies partnership and companionship. The Lovers signify the coming together of two individuals in a mutually supportive and loving relationship, emphasizing the importance of collaboration and cooperation.',
    'upright3': 'Choices: The Lovers upright signifies choices and decisions related to love and relationships. It represents the need to make thoughtful and conscious choices that align with your values and desires.',
    'upright4': 'Harmony: This card represents harmony and balance within relationships. The Lovers signify a sense of unity, where differences are embraced, and love prevails. It suggests the potential for deep emotional connection and understanding.',
    'upright5': 'Alignment: The Lovers upright embodies alignment and soul connection. It signifies finding a partner or relationship that aligns with your true self and values, emphasizing the importance of authenticity and emotional compatibility.',
    'reversed1': 'Disharmony: The Lovers reversed suggests disharmony and discord in relationships. It represents a lack of alignment or compatibility between partners, leading to conflicts and misunderstandings.',
    'reversed2': 'Choices and Indecision: In the reversed position, the Lovers symbolize indecision or difficulty in making choices related to love and relationships. It signifies a struggle in committing or deciding between different options.',
    'reversed3': 'Unhealthy Attachments: This card suggests unhealthy attachments or codependency. The Lovers reversed represents relationships characterized by a lack of independence and a reliance on the other person for validation or self-worth.',
    'reversed4': 'Love Blocks: The Lovers reversed signifies blocks or obstacles to experiencing love and deep connections. It suggests barriers in opening up emotionally or difficulties in forming meaningful relationships.',
    'reversed5': 'Dishonesty: This card represents dishonesty or deceit within relationships. The Lovers reversed signifies a lack of transparency or trust, indicating potential betrayal or hidden agendas. It serves as a warning to be cautious and aware of potential deception.',
    'img': '',
  },
  'the chariot': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The Chariot',
    'description': 'Witness the triumphant arrival of the Chariot, a symbol of determination and victorious drive. Guided by two majestic sphinxes, he charges forward, fearlessly conquering obstacles. The Charioteer\'s armor reflects unwavering strength and willpower. The celestial canopy above signifies cosmic alignment in his favor. His chariot, adorned with sacred symbols, harnesses the opposing forces of yin and yang, balancing their energies. In the realm of the Chariot, relentless ambition merges with disciplined focus, urging you to seize the reins of your destiny and propel yourself towards glorious triumph.',
    'upright1': 'Determination: The Chariot upright represents determination and willpower. It signifies a strong sense of purpose and the drive to overcome obstacles and achieve success.',
    'upright2': 'Control: This card embodies control and mastery over your circumstances. The Chariot signifies the ability to navigate through challenges and maintain a sense of control and direction in life.',
    'upright3': 'Victory: The Chariot upright signifies victory and triumph. It represents achieving desired outcomes and reaching your goals through focused effort and perseverance.',
    'upright4': 'Ambition: This card symbolizes ambition and drive for success. The Chariot signifies a strong desire to achieve greatness and make progress towards personal and professional aspirations.',
    'upright5': 'Forward Movement: The Chariot represents forward movement and progress. It signifies a period of advancement and momentum, propelling you towards your desired destination or future endeavors.',
    'reversed1': 'Lack of Direction: The Chariot reversed suggests a lack of direction or clarity in your goals and aspirations. It signifies a feeling of being lost or uncertain about the path ahead.',
    'reversed2': 'Lack of Control: In the reversed position, the Chariot represents a loss of control or a struggle to maintain stability. It suggests difficulties in managing challenges or external forces that hinder progress.',
    'reversed3': 'Lack of Motivation: This card signifies a lack of motivation or drive. The Chariot reversed suggests a loss of ambition or energy, resulting in a lack of progress or the inability to move forward.',
    'reversed4': 'Inner Conflict: The Chariot reversed represents inner conflict or internal battles. It signifies a struggle between different desires or motivations, leading to indecisiveness or a lack of alignment within yourself.',
    'reversed5': 'Stagnation: This card suggests stagnation or a lack of forward movement. The Chariot reversed signifies being stuck in a state of inertia, where progress and growth are hindered, leading to a sense of frustration or being stuck in a rut.',
    'img': '',
  },
  'strength': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'Strength',
    'description': 'Enter the realm of Strength, where courage reigns and inner fortitude prevails. The lion and the maiden stand as allies, showcasing the harmonious union of power and compassion. Fearlessly, the maiden gently tames the lion\'s wild essence, a testament to her unwavering strength. With a golden crown, she embraces her divine authority. In the realm of Strength, bravery becomes a catalyst for transformation, urging you to embrace your inner power and overcome any challenges that come your way with grace and resilience.',
    'upright1': 'Inner Strength: The Strength upright represents inner strength and courage. It signifies the ability to face challenges with resilience, confidence, and determination.',
    'upright2': 'Courage: This card embodies courage and bravery. The Strength card signifies the willingness to confront fears, overcome obstacles, and stand up for what is right.',
    'upright3': 'Patience: The Strength card symbolizes patience and endurance. It represents the ability to remain calm and composed in the face of adversity, waiting for the right moment to take action.',
    'upright4': 'Compassion: This card signifies compassion and gentleness. The Strength card represents the power of love and understanding, using empathy and kindness to resolve conflicts and build bridges.',
    'upright5': 'Self-Mastery: The Strength upright embodies self-mastery and self-control. It signifies the ability to harness your passions and instincts, channeling them in a positive and balanced way. It represents inner harmony and taming your inner "wild" aspects.',
    'reversed1': 'Lack of Confidence: The Strength reversed suggests a lack of confidence or self-belief. It signifies doubts and insecurities that hinder your ability to face challenges or overcome obstacles.',
    'reversed2': 'Inner Turmoil: In the reversed position, the Strength card represents inner turmoil or a struggle with your emotions. It suggests a lack of emotional stability or difficulty in managing and harnessing your passions and instincts.',
    'reversed3': 'Weakness: This card signifies weakness or a lack of inner strength. The Strength reversed suggests a vulnerability to external pressures or an inability to stand up for yourself in the face of adversity.',
    'reversed4': 'Self-Doubt: The Strength reversed represents self-doubt and a lack of self-trust. It signifies a lack of belief in your abilities or a tendency to underestimate your own power and potential.',
    'reversed5': 'Unresolved Conflict: This card suggests unresolved conflicts or power struggles. The Strength reversed signifies a difficulty in finding a resolution or maintaining inner harmony in challenging situations. It may indicate a need to address and confront these conflicts to regain personal strength.',
    'img': '',
  },
  'the hermit': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The Hermit',
    'description': 'Dive into the realm of the Hermit, a solitary sage on a quest for inner illumination. Cloaked in wisdom, he navigates the path of introspection with a lantern, casting light on hidden truths. His long white beard echoes the depth of his experience, while his staff supports him on his spiritual pilgrimage. In the realm of the Hermit, solitude becomes a sacred refuge for self-discovery. Embrace the wisdom of introspection, and let the glow of your inner lantern guide you towards profound enlightenment and self-realization.',
    'upright1': 'Solitude: The Hermit upright represents solitude and introspection. It signifies a period of seeking inner wisdom and guidance through solitude and self-reflection.',
    'upright2': 'Wisdom: This card embodies wisdom and knowledge. The Hermit signifies the pursuit of deeper understanding, drawing on personal experience and accumulated wisdom to navigate life\'s challenges.',
    'upright3': 'Inner Guidance: The Hermit upright signifies the importance of listening to your inner voice and trusting your intuition. It represents seeking guidance from within and following your own unique path.',
    'upright4': 'Spiritual Quest: This card symbolizes a spiritual quest or journey. The Hermit represents a period of seeking spiritual enlightenment, finding deeper meaning, and connecting with higher truths.',
    'upright5': 'Mentorship: The Hermit upright suggests the presence of a wise mentor or teacher. It signifies the guidance and support of someone with profound knowledge and experience, aiding in personal growth and self-discovery.',
    'reversed1': '',
    'reversed2': '',
    'reversed3': '',
    'reversed4': '',
    'reversed5': '',
    'img': '',
  },
  '': {
    'type': '',
    'suit': '',
    'cardName': '',
    'description': '',
    'upright1': '',
    'upright2': '',
    'upright3': '',
    'upright4': '',
    'upright5': '',
    'reversed1': '',
    'reversed2': '',
    'reversed3': '',
    'reversed4': '',
    'reversed5': '',
    'img': '',
  },
  '': {
    'type': '',
    'suit': '',
    'cardName': '',
    'description': '',
    'upright1': '',
    'upright2': '',
    'upright3': '',
    'upright4': '',
    'upright5': '',
    'reversed1': '',
    'reversed2': '',
    'reversed3': '',
    'reversed4': '',
    'reversed5': '',
    'img': '',
  },
  '': {
    'type': '',
    'suit': '',
    'cardName': '',
    'description': '',
    'upright1': '',
    'upright2': '',
    'upright3': '',
    'upright4': '',
    'upright5': '',
    'reversed1': '',
    'reversed2': '',
    'reversed3': '',
    'reversed4': '',
    'reversed5': '',
    'img': '',
  },
  '': {
    'type': '',
    'suit': '',
    'cardName': '',
    'description': '',
    'upright1': '',
    'upright2': '',
    'upright3': '',
    'upright4': '',
    'upright5': '',
    'reversed1': '',
    'reversed2': '',
    'reversed3': '',
    'reversed4': '',
    'reversed5': '',
    'img': '',
  },

    // '': {
  //   'type': '',
  //   'suit': '',
  //   'cardName': '',
  //   'description': '',
  //   'upright1': '',
  //   'upright2': '',
  //   'upright3': '',
  //   'upright4': '',
  //   'upright5': '',
  //   'reversed1': '',
  //   'reversed2': '',
  //   'reversed3': '',
  //   'reversed4': '',
  //   'reversed5': '',
  //   'img': '',
  // },
  'unknown': {
    'type': 'unknown',
    'cardName': 'unknown',
    'uprightKeywords': 'unknown',
    'reversedKeywords': 'unknown',
    'description': 'unknown',
    'img': 'unknown',
  }  
}

app.get('/', (req,res)=>{
  res.sendFile(__dirname + '/index.html')
})

app.get('/api/:name', (req,res)=>{
  const tarotCards = req.params.name.toLowerCase()
  if(card[tarotCards]){
    res.json(card[tarotCards])
  }else{
    res.json(card['unknown'])
  }
})

app.listen(process.env.PORT || PORT, ()=>{
  console.log(`Woo port ${PORT} is up and running - go catch it!`)
})



