const express = require('express')
const app = express()
const cors = require('cors')
const PORT = 8000

app.use(cors())


const card = {
  'the fool': {
    'type': 'Major Arcana',
    'cardName': 'The Fool',
    'description': 'Behold the Fool, a daring adventurer at the precipice of destiny. With carefree abandon, he stands on the edge, ready to leap into the unknown. Unaware of the imminent plunge, his gaze fixates on the boundless sky. Clutching a humble knapsack, he embraces minimalism and unlimited potential. A white rose embodies his purity, while a loyal canine companion nudges him forward. The looming mountains foretell challenges, yet his unyielding spirit fuels his expedition. With fearless steps, he embarks on a transformative journey, leaving behind the constraints of fear and embracing the magic of the Fool\'s quest.',
    // 'uprightKeywords': 'Spontaneity &#x2022; Innocence &#x2022; Optimism &#x2022; Freedom &#x2022; Beginnings',
    'upright1': 'Spontaneity: The Fool upright represents a carefree and spontaneous nature. It is associated with taking risks and embracing new adventures without fear or hesitation.',
    'upright2': 'Innocence: The Fool embodies a sense of childlike innocence and naivety. It suggests a lack of preconceived notions or biases, allowing for a fresh perspective and open-mindedness.',
    'upright3': 'Optimism: This card radiates positivity and optimism. The Fool upright encourages a hopeful outlook on life, emphasizing the belief that everything will work out for the best.',
    'upright4': 'Freedom: The Fool symbolizes freedom from constraints and limitations. It signifies a willingness to break free from societal norms or expectations, embracing personal freedom and individuality.',
    'upright5': 'Beginnings: The Fool is associated with new beginnings and fresh starts. It represents the start of a journey or a new phase in life, urging you to embrace change and take the first steps towards your goals.',
    'reversed1': 'Recklessness: The Fool reversed indicates a lack of caution or thoughtfulness in your actions. It suggests impulsive behavior and a tendency to act without considering the consequences.',
    'reversed2': 'Foolishness: In the reversed position, the Fool represents poor judgment or decision-making. It signifies a lack of wisdom or understanding, leading to unwise choices or actions.',
    'reversed3': 'Naivety: The Fool reversed suggests a state of being overly trusting or gullible. It signifies a vulnerability to deception or manipulation, as well as a tendency to overlook important details or warning signs.',
    'reversed4': 'Stagnation: This card in reverse can indicate a resistance to change or a fear of taking risks. It suggests a reluctance to embrace new opportunities or step out of your comfort zone, leading to a sense of stagnation or missed chances.',
    'reversed5': 'Consequences: The Fool reversed often signifies facing the consequences of your actions or decisions. It warns of potential setbacks, misunderstandings, or negative outcomes resulting from hasty or ill-considered choices.',
    'img': '/img/the-fool.png',
  },
  'the magician': {
    'type': 'Major Arcana',
    'cardName': 'The Magician',
    'description': 'Witness the Magician, a master of infinite possibilities and conjurer of destiny. With arms outstretched, he bridges the realms of spirit and matter. His touch transforms energy into tangible realities, a conduit of creation. Clad in a robe of purest white, he embodies purity, while his fiery cloak reflects worldly wisdom. Before him, the Tarot symbols await, embodying the elements and his mastery. The infinity symbol above signifies boundless potential, while a self-consuming snake whispers secrets of endless transformation. Amidst blossoming foliage, his visions manifest, a mesmerizing dance of dreams turned into tangible truths.',
    'upright1': 'Mastery: The Magician upright represents a mastery of skills and abilities. It signifies having the knowledge, expertise, and confidence to manifest your desires and goals effectively.',
    'upright2': 'Creativity: This card symbolizes creative energy and the power of imagination. The Magician encourages innovative thinking and resourcefulness in finding unique solutions to challenges.',
    'upright3': 'Manifestation: The Magician upright embodies the ability to manifest your intentions into reality. It signifies the power of focused intention, willpower, and taking action to bring about desired outcomes.',
    'upright4': 'Transformation: The Magician represents a transformative energy that facilitates personal growth and positive change. It suggests harnessing your inner potential and embracing opportunities for self-improvement.',
    'upright5': 'Alignment: This card signifies the alignment of mind, body, and spirit. The Magician upright encourages individuals to tap into your inner wisdom and connect with your higher selves, creating a harmonious balance within yourself and your surroundings.',
    'reversed1': 'Manipulation: The Magician reversed can indicate a tendency towards manipulation or deceit. It suggests the misuse of power or skills for personal gain, leading to dishonesty or trickery.',
    'reversed2': 'Lack of Focus: In the reversed position, the Magician represents a lack of focus or direction. It suggests scattered energy and an inability to harness your abilities effectively, resulting in a lack of progress or achievement.',
    'reversed3': 'Misuse of Power: This card signifies the misuse or abuse of power. It suggests that you may be using your skills or influence in a negative or harmful way, potentially causing harm to others or themselves.',
    'reversed4': 'Ineffectiveness: The Magician reversed represents a lack of effectiveness or inefficiency in your actions. It suggests that despite having the necessary skills or resources, you are unable to utilize them effectively, leading to unsuccessful outcomes or missed opportunities.',
    'reversed5': 'Blocked Potential: This card in reverse can indicate a blockage or suppression of your potential. It suggests a failure to tap into your true abilities or talents, resulting in a sense of stagnation or unfulfilled potential.',
    'img': '',
  },
  'the high priestess': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The High Priestess',
    'description': 'Unveiling the High Priestess, an enchanting guardian of ancient wisdom. Clad in mystic allure, she sits before a veil embellished with tempting pomegranates, concealing the realms of the seen and unseen. Only the bold and initiated may pierce its ethereal barrier. Amidst two majestic pillars, one shrouded in darkness, the other bathed in light, she whispers of profound duality. Surrender to her beckoning embrace, and traverse the hallowed depths where secrets of the universe dance, awaiting those who seek divine revelation.',
    'upright1': 'Intuition: The High Priestess upright represents deep intuition and inner wisdom. It suggests the ability to tap into your subconscious mind and access intuitive insights and knowledge.',
    'upright2': 'Mystery: This card embodies a sense of mystery and hidden knowledge. The High Priestess signifies the presence of secrets, hidden truths, and esoteric wisdom that may be revealed over time.',
    'upright3': 'Feminine Energy: The High Priestess is associated with feminine energy and the divine feminine. It represents intuition, receptivity, and the nurturing aspects of your nature.',
    'upright4': 'Spiritual Connection: This card symbolizes a strong connection to the spiritual realm. It suggests a deep understanding of spiritual matters, meditation, and inner reflection to gain spiritual insights and guidance.',
    'upright5': 'Inner Balance: The High Priestess upright signifies inner balance and harmony. It suggests a state of equilibrium between the conscious and subconscious mind, embracing both rationality and intuition in decision-making and life choices.',
    'reversed1': 'Blocked Intuition: The High Priestess reversed suggests a blockage or suppression of your intuition. It indicates a lack of trust in your inner wisdom and an inability to access or heed intuitive guidance.',
    'reversed2': 'Hidden Knowledge: In the reversed position, the High Priestess represents hidden or obscured knowledge that remains out of reach. It suggests a difficulty in uncovering deeper truths or accessing esoteric wisdom.',
    'reversed3': 'Lack of Understanding: This card signifies a lack of understanding or confusion. The High Priestess reversed suggests a struggle to grasp the deeper meaning or significance of certain experiences or situations.',
    'reversed4': 'Disconnection from Spirituality: In the reversed position, the High Priestess indicates a disconnection from spirituality or a lack of spiritual exploration. It suggests a diminished connection to your higher self and a disregard for inner reflection or spiritual practices.',
    'reversed5': 'Imbalance: The High Priestess reversed suggests an imbalance between the conscious and subconscious mind. It signifies a lack of inner harmony, where rationality and intuition are at odds, leading to confusion or indecisiveness.',
    'img': '',
  },
  'the empress': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The Empress',
    'description': 'Enter the realm of the Empress, a radiant force of creation and nurturing abundance. Adorned in lush greenery, she sits upon a throne of blossoming beauty. The embodiment of fertility, she nurtures life\'s bountiful harvest. Golden wheat fields sway in homage to her abundant grace. Her loving gaze and compassionate embrace radiate maternal power. With each breath, she breathes life into dreams and manifests them into reality. The Empress, a goddess of earthly delights, invites you to embrace your creative potential and immerse yourself in the abundant tapestry of existence.',
    'upright1': 'Fertility: The Empress upright represents fertility, both in terms of physical fertility and the ability to nurture and create. It signifies a time of abundance, growth, and the potential for new beginnings.',
    'upright2': 'Nurturing: This card embodies nurturing and maternal energy. The Empress signifies a caring and compassionate nature, offering support and guidance to others. It represents the ability to create a loving and nurturing environment.',
    'upright3': 'Creativity: The Empress upright symbolizes creativity and artistic expression. It suggests a time of inspiration and the birth of new ideas. This card encourages embracing your creative abilities and exploring artistic endeavors.',
    'upright4': 'Abundance: This card represents abundance and prosperity. The Empress signifies a time of material and emotional abundance, where resources and opportunities are readily available. It suggests a sense of wealth and fulfillment.',
    'upright5': 'Harmony: The Empress upright signifies harmony and balance. It represents a state of equilibrium and contentment, where you feels connected to the natural rhythms of life. This card suggests finding harmony within yourself and in relationships with others.',
    'reversed1': 'Lack of Nurturing: The Empress reversed suggests a lack of nurturing or neglectful behavior. It signifies a failure to provide care and support to yourself or others. It may indicate difficulties in creating a loving and nurturing environment.',
    'reversed2': 'Creative Block: In the reversed position, the Empress represents a creative block or a struggle to express yourself artistically. It suggests a lack of inspiration or difficulty in manifesting creative ideas.',
    'reversed3': 'Scarcity: This card indicates a sense of scarcity or a lack of abundance. The Empress reversed signifies a period of limited resources, both material and emotional. It may suggest financial challenges or a feeling of emptiness.',
    'reversed4': 'Disharmony: The Empress reversed represents disharmony and imbalance. It suggests a lack of harmony within yourself or in relationships. It may indicate conflicts, discord, or a sense of disconnection from the natural rhythms of life.',
    'reversed5': 'Self-neglect: This card suggests self-neglect or a disregard for self-care. The Empress reversed signifies a tendency to put others\' needs before your own, leading to a depletion of energy and a lack of personal fulfillment.',
    'img': '',
  },
  'the emperor': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The Emperor',
    'description': 'Commanding and resolute, the Emperor rules with unwavering authority. Seated on a throne of strength, his presence exudes power and leadership. Clad in regal armor, he channels the fiery energy of ambition. A long white beard symbolizes wisdom earned through experience. His gaze penetrates, as he forges order from chaos. The ram\'s heads on his throne represent his fierce determination. The Emperor, a master of structure and discipline, implores you to embrace your inner strength and embrace the challenges that lie ahead with unwavering confidence.',
    'upright1': 'Authority: The Emperor upright represents authority and leadership. It symbolizes a strong and confident individual who is capable of taking charge and making decisions with clarity and conviction.',
    'upright2': 'Structure: This card embodies structure and organization. The Emperor signifies the establishment of order and systems, providing a solid foundation for stability and success.',
    'upright3': 'Power: The Emperor upright signifies personal power and control. It represents the ability to assert yourself and influence your surroundings, displaying strength and resilience in the face of challenges.',
    'upright4': 'Discipline: This card represents discipline and self-control. The Emperor signifies the importance of setting boundaries, adhering to rules, and maintaining a focused approach in order to achieve goals.',
    'upright5': 'Responsibility: The Emperor upright embodies responsibility and accountability. It signifies taking on leadership roles, fulfilling obligations, and being accountable for your actions and decisions. This card emphasizes the need for wise and responsible governance.',
    'reversed1': 'Authoritarianism: The Emperor reversed suggests a misuse or abuse of authority. It signifies a tendency towards oppressive or dictatorial behavior, where power is exercised in a domineering or controlling manner.',
    'reversed2': 'Lack of Structure: In the reversed position, the Emperor represents a lack of structure or disorganization. It signifies a difficulty in establishing and maintaining order, leading to chaos or instability.',
    'reversed3': 'Power Struggles: This card suggests power struggles or challenges to authority. The Emperor reversed signifies conflicts or resistance to established leadership, often resulting from a lack of trust or dissatisfaction with the current structure.',
    'reversed4': 'Lack of Discipline: In the reversed position, the Emperor signifies a lack of discipline or self-control. It suggests a tendency towards impulsiveness or erratic behavior, leading to a lack of focus or direction.',
    'reversed5': 'Irresponsibility: The Emperor reversed embodies a lack of responsibility or accountability. It suggests an avoidance of leadership roles or a failure to fulfill obligations and duties. This card highlights a lack of maturity or unwillingness to take on necessary responsibilities.',
    'img': '',
  },
  'the hierophant': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The Hierophant',
    'description': 'Enter the realm of the Hierophant, a beacon of spiritual wisdom and divine guidance. Seated on a sacred throne, he embodies the essence of tradition and ritual. Clad in robes adorned with sacred symbols, his presence invokes reverence. The keys at his feet symbolize unlocking hidden knowledge. Two acolytes beside him seek his teachings. The Hierophant, a conduit of ancient wisdom, invites you to embrace tradition while seeking your own spiritual truths. Through his guidance, you\'ll unravel the profound mysteries of existence and find harmony between tradition and personal enlightenment.',
    'upright1': 'Tradition: The Hierophant upright represents tradition and conformity. It signifies adherence to established norms, rituals, and cultural or religious customs.',
    'upright2': 'Spiritual Guidance: This card embodies spiritual guidance and wisdom. The Hierophant signifies the presence of a spiritual teacher or mentor who imparts valuable knowledge and guidance on matters of spirituality and belief systems.',
    'upright3': 'Authority: The Hierophant upright signifies authority and leadership in spiritual or religious matters. It represents an individual or institution with a significant role in providing guidance, interpreting doctrines, or upholding religious teachings.',
    'upright4': 'Conformity: This card suggests a need for conformity or adherence to societal norms. The Hierophant signifies a desire to fit in or seek validation through adhering to established structures and belief systems.',
    'upright5': 'Rituals and Ceremonies: The Hierophant upright embodies rituals, ceremonies, and formalities. It represents the importance of participating in meaningful rituals or ceremonies to foster spiritual connection and growth. This card emphasizes the significance of tradition and shared experiences within a community or group. ',
    'reversed1': 'Nonconformity: The Hierophant reversed signifies a rejection of traditional norms and a resistance to conformity. It suggests a desire to break free from established structures and explore alternative paths or belief systems.',
    'reversed2': 'Unconventional Spirituality: In the reversed position, the Hierophant represents a departure from mainstream spirituality or organized religion. It suggests a personal exploration of spirituality that diverges from established practices or doctrines.',
    'reversed3': 'Questioning Authority: This card suggests a skepticism towards authority figures or institutions. The Hierophant reversed signifies a tendency to question the teachings and guidance of traditional authorities, seeking your own truths and beliefs.',
    'reversed4': 'Unorthodox Practices: The Hierophant reversed embodies unorthodox or alternative practices. It represents a willingness to explore different spiritual paths or unconventional methods of seeking enlightenment or inner wisdom.',
    'reversed5': 'Spirituality in Personal Terms: This card suggests an individualized approach to spirituality. The Hierophant reversed signifies the importance of finding your own spiritual path and defining your beliefs and practices based on personal experiences and insights.',
    'img': '',
  },
  'the lovers': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The Lovers',
    'description': 'Embark on the journey of the Lovers, where passion and harmony entwine. Two souls stand at the precipice of profound connection. Their gazes lock, igniting a flame that transcends the physical. Above, an angel blesses their union, whispering celestial guidance. The intertwined trees symbolize the intertwining of their destinies. Eros\' arrow strikes deep, forging a bond that defies time and space. In the realm of the Lovers, love conquers all, urging you to embrace the transformative power of true connection and celebrate the harmonious dance of hearts entwined.',
    'upright1': 'Love: The Lovers upright represents love in all its forms, including romantic love, deep connections, and harmonious relationships. It signifies a union of hearts and a deep emotional bond.',
    'upright2': 'Partnership: This card embodies partnership and companionship. The Lovers signify the coming together of two individuals in a mutually supportive and loving relationship, emphasizing the importance of collaboration and cooperation.',
    'upright3': 'Choices: The Lovers upright signifies choices and decisions related to love and relationships. It represents the need to make thoughtful and conscious choices that align with your values and desires.',
    'upright4': 'Harmony: This card represents harmony and balance within relationships. The Lovers signify a sense of unity, where differences are embraced, and love prevails. It suggests the potential for deep emotional connection and understanding.',
    'upright5': 'Alignment: The Lovers upright embodies alignment and soul connection. It signifies finding a partner or relationship that aligns with your true self and values, emphasizing the importance of authenticity and emotional compatibility.',
    'reversed1': 'Disharmony: The Lovers reversed suggests disharmony and discord in relationships. It represents a lack of alignment or compatibility between partners, leading to conflicts and misunderstandings.',
    'reversed2': 'Choices and Indecision: In the reversed position, the Lovers symbolize indecision or difficulty in making choices related to love and relationships. It signifies a struggle in committing or deciding between different options.',
    'reversed3': 'Unhealthy Attachments: This card suggests unhealthy attachments or codependency. The Lovers reversed represents relationships characterized by a lack of independence and a reliance on the other person for validation or self-worth.',
    'reversed4': 'Love Blocks: The Lovers reversed signifies blocks or obstacles to experiencing love and deep connections. It suggests barriers in opening up emotionally or difficulties in forming meaningful relationships.',
    'reversed5': 'Dishonesty: This card represents dishonesty or deceit within relationships. The Lovers reversed signifies a lack of transparency or trust, indicating potential betrayal or hidden agendas. It serves as a warning to be cautious and aware of potential deception.',
    'img': '',
  },
  'the chariot': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The Chariot',
    'description': 'Witness the triumphant arrival of the Chariot, a symbol of determination and victorious drive. Guided by two majestic sphinxes, he charges forward, fearlessly conquering obstacles. The Charioteer\'s armor reflects unwavering strength and willpower. The celestial canopy above signifies cosmic alignment in his favor. His chariot, adorned with sacred symbols, harnesses the opposing forces of yin and yang, balancing their energies. In the realm of the Chariot, relentless ambition merges with disciplined focus, urging you to seize the reins of your destiny and propel yourself towards glorious triumph.',
    'upright1': 'Determination: The Chariot upright represents determination and willpower. It signifies a strong sense of purpose and the drive to overcome obstacles and achieve success.',
    'upright2': 'Control: This card embodies control and mastery over your circumstances. The Chariot signifies the ability to navigate through challenges and maintain a sense of control and direction in life.',
    'upright3': 'Victory: The Chariot upright signifies victory and triumph. It represents achieving desired outcomes and reaching your goals through focused effort and perseverance.',
    'upright4': 'Ambition: This card symbolizes ambition and drive for success. The Chariot signifies a strong desire to achieve greatness and make progress towards personal and professional aspirations.',
    'upright5': 'Forward Movement: The Chariot represents forward movement and progress. It signifies a period of advancement and momentum, propelling you towards your desired destination or future endeavors.',
    'reversed1': 'Lack of Direction: The Chariot reversed suggests a lack of direction or clarity in your goals and aspirations. It signifies a feeling of being lost or uncertain about the path ahead.',
    'reversed2': 'Lack of Control: In the reversed position, the Chariot represents a loss of control or a struggle to maintain stability. It suggests difficulties in managing challenges or external forces that hinder progress.',
    'reversed3': 'Lack of Motivation: This card signifies a lack of motivation or drive. The Chariot reversed suggests a loss of ambition or energy, resulting in a lack of progress or the inability to move forward.',
    'reversed4': 'Inner Conflict: The Chariot reversed represents inner conflict or internal battles. It signifies a struggle between different desires or motivations, leading to indecisiveness or a lack of alignment within yourself.',
    'reversed5': 'Stagnation: This card suggests stagnation or a lack of forward movement. The Chariot reversed signifies being stuck in a state of inertia, where progress and growth are hindered, leading to a sense of frustration or being stuck in a rut.',
    'img': '',
  },
  'strength': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'Strength',
    'description': 'Enter the realm of Strength, where courage reigns and inner fortitude prevails. The lion and the maiden stand as allies, showcasing the harmonious union of power and compassion. Fearlessly, the maiden gently tames the lion\'s wild essence, a testament to her unwavering strength. With a golden crown, she embraces her divine authority. In the realm of Strength, bravery becomes a catalyst for transformation, urging you to embrace your inner power and overcome any challenges that come your way with grace and resilience.',
    'upright1': 'Inner Strength: The Strength upright represents inner strength and courage. It signifies the ability to face challenges with resilience, confidence, and determination.',
    'upright2': 'Courage: This card embodies courage and bravery. The Strength card signifies the willingness to confront fears, overcome obstacles, and stand up for what is right.',
    'upright3': 'Patience: The Strength card symbolizes patience and endurance. It represents the ability to remain calm and composed in the face of adversity, waiting for the right moment to take action.',
    'upright4': 'Compassion: This card signifies compassion and gentleness. The Strength card represents the power of love and understanding, using empathy and kindness to resolve conflicts and build bridges.',
    'upright5': 'Self-Mastery: The Strength upright embodies self-mastery and self-control. It signifies the ability to harness your passions and instincts, channeling them in a positive and balanced way. It represents inner harmony and taming your inner "wild" aspects.',
    'reversed1': 'Lack of Confidence: The Strength reversed suggests a lack of confidence or self-belief. It signifies doubts and insecurities that hinder your ability to face challenges or overcome obstacles.',
    'reversed2': 'Inner Turmoil: In the reversed position, the Strength card represents inner turmoil or a struggle with your emotions. It suggests a lack of emotional stability or difficulty in managing and harnessing your passions and instincts.',
    'reversed3': 'Weakness: This card signifies weakness or a lack of inner strength. The Strength reversed suggests a vulnerability to external pressures or an inability to stand up for yourself in the face of adversity.',
    'reversed4': 'Self-Doubt: The Strength reversed represents self-doubt and a lack of self-trust. It signifies a lack of belief in your abilities or a tendency to underestimate your own power and potential.',
    'reversed5': 'Unresolved Conflict: This card suggests unresolved conflicts or power struggles. The Strength reversed signifies a difficulty in finding a resolution or maintaining inner harmony in challenging situations. It may indicate a need to address and confront these conflicts to regain personal strength.',
    'img': '',
  },
  'the hermit': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The Hermit',
    'description': 'Dive into the realm of the Hermit, a solitary sage on a quest for inner illumination. Cloaked in wisdom, he navigates the path of introspection with a lantern, casting light on hidden truths. His long white beard echoes the depth of his experience, while his staff supports him on his spiritual pilgrimage. In the realm of the Hermit, solitude becomes a sacred refuge for self-discovery. Embrace the wisdom of introspection, and let the glow of your inner lantern guide you towards profound enlightenment and self-realization.',
    'upright1': 'Solitude: The Hermit upright represents solitude and introspection. It signifies a period of seeking inner wisdom and guidance through solitude and self-reflection.',
    'upright2': 'Wisdom: This card embodies wisdom and knowledge. The Hermit signifies the pursuit of deeper understanding, drawing on personal experience and accumulated wisdom to navigate life\'s challenges.',
    'upright3': 'Inner Guidance: The Hermit upright signifies the importance of listening to your inner voice and trusting your intuition. It represents seeking guidance from within and following your own unique path.',
    'upright4': 'Spiritual Quest: This card symbolizes a spiritual quest or journey. The Hermit represents a period of seeking spiritual enlightenment, finding deeper meaning, and connecting with higher truths.',
    'upright5': 'Mentorship: The Hermit upright suggests the presence of a wise mentor or teacher. It signifies the guidance and support of someone with profound knowledge and experience, aiding in personal growth and self-discovery.',
    'reversed1': 'Isolation: The Hermit reversed suggests a prolonged state of isolation or social withdrawal. It represents a disconnection from others and a reluctance to seek or accept external help or guidance.',
    'reversed2': 'Loneliness: In the reversed position, the Hermit signifies feelings of loneliness or a sense of being cut off from the world. It suggests a lack of meaningful connections or difficulty in forming relationships.',
    'reversed3': 'Lost Direction: This card represents a loss of direction or purpose. The Hermit reversed suggests a feeling of being lost or confused, with a lack of clarity about your path or goals.',
    'reversed4': 'Avoidance: The Hermit reversed signifies a tendency to avoid introspection or self-reflection. It suggests a resistance to facing inner truths or avoiding necessary periods of solitude and introspection for personal growth.',
    'reversed5': 'Lack of Guidance: In the reversed position, the Hermit indicates a lack of guidance or mentorship. It suggests a difficulty in finding wise counsel or seeking guidance from others, leading to a sense of uncertainty or feeling adrift.',
    'img': '',
  },
  'wheel of fortune': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'Wheel Of Fortune',
    'description': 'Behold the Wheel of Fortune, a captivating dance of destiny and cosmic cycles. Spinning ceaselessly, it weaves the tapestry of fate. Ascending on the wheel\'s crest, fortunes rise, while those beneath witness their ebb. The mystical creatures adorning its edges symbolize the eternal dance of chance and fate. In the realm of the Wheel of Fortune, life\'s unpredictable rhythms guide us, urging us to embrace the ever-changing tides. Surrender to its enchanting rhythm, and unlock the secrets of divine timing, as destiny unfolds its mesmerizing symphony.',
    'upright1': 'Destiny: The Wheel of Fortune upright represents the concept of destiny and the unfolding of fate. It signifies that life is governed by cycles of ups and downs and that events are influenced by factors beyond our control.',
    'upright2': 'Change: This card embodies change and transformation. The Wheel of Fortune signifies that life is constantly evolving, and situations can shift unexpectedly. It represents embracing change and being open to new opportunities.',
    'upright3': 'Luck: The Wheel of Fortune upright symbolizes luck and fortune. It suggests that favorable circumstances or unexpected opportunities may arise in your life, bringing positive outcomes.',
    'upright4': 'Cycles: This card represents the cyclical nature of life. The Wheel of Fortune signifies that everything in life operates in cycles, with periods of growth, decline, and renewal. It emphasizes the importance of understanding and accepting these cycles.',
    'upright5': 'Synchronicity: The Wheel of Fortune signifies synchronicity and the interplay of events and energies in the universe. It suggests that there are underlying connections and meaningful coincidences at play, guiding your path and aligning with the flow of life.',
    'reversed1': 'Stagnation: The Wheel of Fortune reversed suggests a state of stagnation or feeling stuck. It represents a lack of progress or difficulty in moving forward due to external or internal factors.',
    'reversed2': 'Resistance to Change: In the reversed position, this card signifies resistance to change. It suggests a reluctance to embrace the natural cycles of life or a fear of stepping into the unknown.',
    'reversed3': 'Unpredictability: The Wheel of Fortune reversed symbolizes unpredictability and a lack of control over external circumstances. It indicates that events may be more chaotic or uncertain, making it challenging to anticipate or navigate through them.',
    'reversed4': 'Misfortune: This card represents a period of misfortune or unfortunate events. The Wheel of Fortune reversed suggests that luck may not be in your favor, and unexpected challenges or setbacks may arise.',
    'reversed5': 'Breaking Cycles: In the reversed position, the Wheel of Fortune signifies an opportunity to break negative cycles or patterns. It suggests a need for conscious awareness and deliberate action to create positive change and break free from repetitive cycles of outcomes.',
    'img': '',
  },
  'justice': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'Justice',
    'description': 'Enter the realm of Justice, where fairness and truth hold sway. Seated upon her throne, the scales of balance rest in her steady hand. Blindfolded, she impartially weighs each decision. The sword she wields is swift and sharp, cutting through deceit and revealing justice\'s true path. In the realm of Justice, right and wrong find equilibrium, and karma unveils its unforgiving embrace. Embrace the power of integrity and accountability, for in the realm of Justice, the cosmic scales ensure that truth prevails and harmony is restored.',
    'upright1': 'Fairness: The Justice upright represents fairness and impartiality. It signifies the need for balance and equality in all aspects of life, including decision-making, relationships, and justice systems.',
    'upright2': 'Accountability: This card embodies accountability and taking responsibility for your actions. The Justice card signifies the consequences and repercussions of your choices and behaviors.',
    'upright3': 'Truth: The Justice card represents truth and honesty. It signifies the importance of seeking and upholding truth, both within yourself and in external situations. It emphasizes the power of integrity and transparency.',
    'upright4': 'Legal Matters: This card is associated with legal matters and the justice system. The Justice upright signifies the need for legal proceedings to be conducted fairly, and it can suggest positive outcomes or resolutions in legal disputes.',
    'upright5': 'Balancing Choices: The Justice card represents the need to weigh options and make balanced decisions. It signifies the importance of considering different perspectives and finding a middle ground when faced with conflicting choices or situations.',
    'reversed1': 'Unfairness: The Justice reversed suggests unfairness and imbalance. It signifies situations where justice is compromised or where decisions and actions lack fairness and impartiality.',
    'reversed2': 'Dishonesty: In the reversed position, the Justice card represents dishonesty or deceit. It suggests the presence of lies, deception, or manipulation in a situation, making it challenging to find truth and uphold justice.',
    'reversed3': 'Lack of Accountability: This card signifies a lack of accountability or evasion of responsibility. The Justice reversed suggests a refusal to take ownership of your actions or face the consequences of your choices.',
    'reversed4': 'Legal Injustice: The Justice reversed can represent legal injustice or unfair legal outcomes. It suggests that legal proceedings may be biased, unjust, or improperly conducted, leading to unjust results.',
    'reversed5': 'Imbalance: This card embodies imbalance and lack of equilibrium. The Justice reversed signifies situations where there is a lack of fairness, harmony, or balance. It may indicate a need to restore balance and rectify injustices.',
    'img': '',
  },
  'the hanged man': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The Hanged Man',
    'description': 'Suspended in a moment of profound surrender, the Hanged Man. Bound upside down, he embraces the transformative power of sacrifice. Through his inverted perspective, new insights emerge. Serene and introspective, he finds liberation within restriction. In the realm of the Hanged Man, release attachments, and embrace the wisdom of letting go. Through surrender, you unlock a world of divine revelation, transcending limitations to gain a fresh outlook. Embrace the transformative journey of the Hanged Man, and discover the hidden blessings that await in the depths of surrender.',
    'upright1': 'Surrender: The Hanged Man upright represents surrender and letting go. It signifies the willingness to release control, expectations, and attachments in order to gain a new perspective or insight.',
    'upright2': 'Suspension: This card embodies suspension and a state of pause or waiting. The Hanged Man signifies a period of introspection and contemplation, where you may need to step back from action and observe from a different vantage point.',
    'upright3': 'Sacrifice: The Hanged Man represents sacrifice and selflessness. It suggests the willingness to make personal sacrifices or endure temporary discomfort for the sake of greater growth or spiritual understanding.',
    'upright4': 'Perspective Shift: This card symbolizes a shift in perspective or a change in how you perceives the world. The Hanged Man signifies the need to look at things from a different angle, challenge conventional thinking, and embrace alternative viewpoints.',
    'upright5': 'Enlightenment: The Hanged Man upright signifies the potential for spiritual enlightenment and profound wisdom. It represents a transformative journey of self-discovery and inner illumination, gained through surrender and open-mindedness.',
    'reversed1': 'Resistance: The Hanged Man reversed suggests resistance to change or a reluctance to let go. It represents a stubbornness or unwillingness to embrace new perspectives or release attachments that may be hindering personal growth.',
    'reversed2': 'Stagnation: This card signifies a state of stagnation or being stuck. The Hanged Man reversed represents a lack of progress or movement, often due to resistance or fear of stepping out of your comfort zone.',
    'reversed3': 'Lack of Surrender: In the reversed position, the Hanged Man suggests a resistance to surrendering or letting go of control. It signifies a struggle to release control and trust in the natural flow of life, resulting in a sense of being trapped or restricted.',
    'reversed4': 'Narrow Perspective: The Hanged Man reversed symbolizes a limited or narrow perspective. It represents an inability or unwillingness to see alternative viewpoints or consider different possibilities, which may hinder personal growth and understanding.',
    'reversed5': 'Delayed Enlightenment: This card suggests a delay in achieving spiritual enlightenment or gaining deeper insights. The Hanged Man reversed signifies obstacles or internal resistance that prevent the individual from experiencing the transformative journey associated with this card in its upright position.',
    'img': '',
  },
  'death': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'Death',
    'description': 'Step into the realm of Death, where endings give birth to new beginnings. Cloaked in black, Death emerges as a catalyst for transformation. A scythe in hand, he cuts through the old, paving the way for rebirth. The withered sun on the horizon symbolizes the completion of a cycle. In the realm of Death, release what no longer serves you, surrender to the inevitable cycles of life, and embrace the beauty of impermanence. From the ashes of the old, a phoenix rises, promising renewal and profound metamorphosis.',
    'upright1': 'Step into the realm of Death, where endings give birth to new beginnings. Cloaked in black, Death emerges as a catalyst for transformation. A scythe in hand, he cuts through the old, paving the way for rebirth. The withered sun on the horizon symbolizes the completion of a cycle. In the realm of Death, release what no longer serves you, surrender to the inevitable cycles of life, and embrace the beauty of impermanence. From the ashes of the old, a phoenix rises, promising renewal and profound metamorphosis.',
    'upright2': 'Rebirth: This card embodies rebirth and renewal. The Death card signifies the shedding of old patterns, beliefs, or relationships, allowing for a fresh start and the opportunity to embrace new possibilities.',
    'upright3': 'Transition: The Death card symbolizes a transition or passage from one state to another. It represents a period of significant transition and adjustment, often accompanied by inner reflection and personal growth.',
    'upright4': 'Letting Go: This card signifies the need to let go of attachments or aspects of life that no longer serve a purpose. The Death upright suggests releasing what is no longer needed to create space for new experiences and opportunities.',
    'upright5': 'Liberation: The Death card represents liberation and liberation from the past or self-imposed limitations. It signifies breaking free from old patterns, habits, or beliefs that have held you back, leading to a sense of freedom and empowerment.',
    'reversed1': 'Resistance to Change: The Death reversed suggests a resistance to change or an unwillingness to let go of old patterns or situations. It represents a fear of transformation and a clinging to familiar but stagnant circumstances.',
    'reversed2': 'Stagnation: This card signifies a state of stagnation or being stuck in a phase of life. The Death reversed represents a lack of growth or progress due to an aversion to necessary changes or an inability to move forward.',
    'reversed3': 'Fear of Endings: In the reversed position, the Death card symbolizes a fear of endings or a reluctance to embrace necessary closures. It suggests holding onto situations or relationships that have reached their natural end, resulting in an inability to move into new phases of life.',
    'reversed4': 'Resisting Transformation: The Death reversed represents resisting personal transformation or avoiding the necessary inner work. It signifies a reluctance to let go of old identities, beliefs, or behaviors that are preventing growth and evolution.',
    'reversed5': 'Delayed Rebirth: This card suggests a delay in experiencing the transformative rebirth associated with the Death card in its upright position. The Death reversed signifies being stuck in a state of limbo or resisting the necessary changes that would lead to personal renewal and growth.',
    'img': '',
  },

  'temperance': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'Temperance',
    'description': 'Enter the realm of Temperance, where harmony and balance intertwine. With grace, an angelic figure delicately pours water between two vessels, symbolizing the merging of opposing forces. One foot stands on solid ground, while the other touches the tranquil stream. In the realm of Temperance, moderation reigns, blending fiery passions with tranquil serenity. Find equilibrium within, embracing the art of patience and finding solace in the ebb and flow of life\'s currents. Through harmonious integration, you discover the transformative alchemy that brings inner peace and divine serenity.',
    'upright1': 'Balance: The Temperance upright represents finding balance and harmony in all aspects of life. It signifies the need for moderation, patience, and integration, allowing for a smooth flow of energies and experiences.',
    'upright2': 'Healing: This card embodies healing and restoration. The Temperance card suggests the need to find inner peace and emotional healing by blending opposing forces and finding equilibrium.',
    'upright3': 'Adaptability: The Temperance card signifies adaptability and flexibility. It represents the ability to navigate through life\'s challenges with grace and resilience, adjusting to changing circumstances while maintaining inner stability.',
    'upright4': 'Divine Guidance: This card symbolizes divine guidance and spiritual support. The Temperance upright suggests connecting with higher wisdom or seeking guidance from spiritual sources to navigate life\'s ups and downs.',
    'upright5': 'Moderation: The Temperance card represents moderation in all things. It encourages finding a middle ground and avoiding extremes, fostering a balanced approach to life\'s pleasures and responsibilities.',
    'reversed1': 'Imbalance: The Temperance reversed suggests a lack of balance or harmony. It represents a difficulty in finding moderation and integration, leading to extremes or instability in various areas of life.',
    'reversed2': 'Impatience: This card signifies impatience and a lack of tolerance. The Temperance reversed suggests a tendency to rush or seek quick fixes, disregarding the need for patience and gradual progress.',
    'reversed3': 'Disharmony: In the reversed position, the Temperance card represents disharmony or conflicts. It signifies difficulties in finding common ground or reconciling opposing forces, resulting in tension or discord.',
    'reversed4': 'Excess: This card symbolizes excessiveness or overindulgence. The Temperance reversed suggests a lack of self-control or an imbalance in your desires, leading to overconsumption or addictive behaviors.',
    'reversed5': 'Lack of Adaptability: The Temperance reversed signifies a resistance to change or an inability to adapt to new circumstances. It suggests a rigid mindset or an aversion to embracing different perspectives, hindering personal growth and adaptability.',
    'img': '',
  },


  'the devil': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The Devil',
    'description': 'Descend into the realm of the Devil, where desires hold sway and temptation entices. Amidst smoldering flames, a figure of power and allure emerges, captivating all who dare to gaze. Chains bind those who succumb to their baser instincts, while the torch of enlightenment burns in the background, reminding of the path to liberation. In the realm of the Devil, shadows dance and illusions seduce, testing your resolve. Unmask the chains that bind, embrace your inner strength, and transcend the allure of temptation, for true liberation lies in breaking free from self-imposed limitations.',
    'upright1': 'Temptation: The Devil upright represents temptation and seduction. It signifies the allure of material desires, unhealthy attachments, or addictive behaviors that may lead you astray.',
    'upright2': 'Bondage: This card embodies bondage or being trapped in unhealthy patterns or relationships. The Devil upright signifies the need to break free from self-imposed limitations or destructive influences that keep you bound.',
    'upright3': 'Shadow Self: The Devil card symbolizes the shadow self and the darker aspects of human nature. It represents confronting and integrating your inner demons, fears, and unresolved issues for personal growth and transformation.',
    'upright4': 'Materialism: This card signifies excessive materialism and a focus on material possessions or external gratification. The Devil upright warns against becoming overly attached to worldly desires or prioritizing material gain above spiritual or emotional well-being.',
    'upright5': 'Self-Destruction: The Devil upright suggests the potential for self-destructive behavior or self-sabotage. It serves as a warning to be mindful of your actions and choices to avoid detrimental consequences and negative outcomes.',
    'reversed1': 'Liberation: The Devil reversed represents liberation from bondage or unhealthy attachments. It signifies breaking free from destructive patterns, releasing yourself from the influence of negative forces, and reclaiming personal power.',
    'reversed2': 'Release: This card embodies release and letting go of self-imposed limitations or harmful influences. The Devil reversed suggests shedding the chains of unhealthy habits, beliefs, or relationships to embrace a path of freedom and self-discovery.',
    'reversed3': 'Overcoming Temptation: The Devil reversed symbolizes overcoming temptation and resisting negative influences. It signifies the strength to resist the allure of harmful behaviors or desires that may lead you astray from their true path.',
    'reversed4': 'Personal Empowerment: This card signifies personal empowerment and taking control of your life. The Devil reversed suggests reclaiming personal sovereignty, making conscious choices, and aligning with your values and authentic self.',
    'reversed5': 'Breaking Cycles: The Devil reversed represents the opportunity to break free from repetitive patterns or cycles of self-destructive behavior. It signifies a chance to break away from negative habits, thoughts, or relationships that hinder personal growth and progress.',
    'img': '',
  },

  'the tower': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The Tower',
    'description': 'Witness the Tower, a cataclysmic force shattering foundations and disrupting the status quo. Lightning strikes the towering structure, setting ablaze what once stood firm. From chaos emerges rebirth. In the realm of the Tower, illusions crumble, revealing truth\'s unyielding light. Embrace the destruction, for amidst the ruins lies the opportunity to rebuild, stronger and wiser. Release attachments, surrender to the divine disruption, and embrace the transformative power of upheaval. From the ashes of the old, a phoenix soars, reminding you that even in destruction, renewal awaits.',
    'upright1': 'Sudden Upheaval: The Tower upright represents sudden and dramatic upheaval or disruption. It signifies a major shake-up or unexpected event that shatters existing structures and routines, challenging the status quo.',
    'upright2': 'Destruction: This card embodies destruction and the dismantling of old systems, beliefs, or relationships. The Tower upright signifies the need to tear down what no longer serves a purpose to make way for new beginnings and growth.',
    'upright3': 'Liberation: The Tower upright symbolizes liberation and breaking free from confining circumstances or limiting beliefs. It represents an opportunity for personal liberation, allowing you to shed old patterns and embrace a more authentic path.',
    'upright4': 'Awakening: This card signifies an awakening or realization triggered by a significant event. The Tower upright represents a moment of profound insight or revelation that leads to a new understanding of yourself or the world.',
    'upright5': 'Divine Intervention: The Tower upright suggests the intervention of higher forces or divine intervention in your life. It represents a transformative experience that is ultimately for the greater good, even if it may initially feel chaotic or disruptive.',
    'reversed1': 'Avoidance: The Tower reversed signifies a tendency to avoid or suppress necessary changes or upheavals in your life. It suggests a reluctance to confront or address underlying issues, which can lead to a buildup of tension or explosive situations.',
    'reversed2': 'Temporary Stability: This card represents temporary stability or the illusion of security. The Tower reversed suggests a false sense of security or the delay of inevitable change, creating a potential for a more significant and unexpected disruption in the future.',
    'reversed3': 'Resistance to Transformation: In the reversed position, the Tower signifies a resistance to personal transformation or a fear of the unknown. It suggests a reluctance to let go of outdated structures or belief systems, hindering personal growth and evolution.',
    'reversed4': 'Release of Repressed Emotions: The Tower reversed can represent the release of repressed emotions or suppressed energies. It signifies a breaking down of emotional barriers or past traumas, leading to an eventual catharsis or emotional release.',
    'reversed5': 'Gradual Change: This card suggests a slower or more gradual process of change or upheaval. The Tower reversed signifies a gentler transformation, where shifts occur over time rather than in a sudden and dramatic manner as seen in the upright position of the card.',
    'img': '',
  },

  'the star': {
    'type': 'Major Arcana',
    'suit': '',
    'cardName': 'The Star',
    'description': 'Gaze upon the Star, a celestial beacon guiding souls towards hope and renewal. Illuminating the night sky, she radiates serenity and inspiration. As water flows, she pours abundant blessings upon the earth. Naked and vulnerable, she embraces authenticity. In the realm of the Star, dreams take flight, and inner desires manifest. Trust in the guiding light of your aspirations, for even in the darkest moments, the Star reminds you that you are capable of shining brightly and finding solace in the embrace of universal love.',
    'upright1': 'Hope: The Star upright represents hope and optimism. It signifies a sense of faith in the future, even in the midst of challenges or difficult times. It symbolizes a guiding light that brings reassurance and inspires confidence.',
    'upright2': 'Inspiration: This card embodies inspiration and creative energy. The Star signifies a connection to your inner guidance and intuition, leading to inspired ideas, visions, and a renewed sense of purpose.',
    'upright3': 'Healing: The Star card represents healing and restoration. It signifies a period of emotional, spiritual, or physical healing, bringing about a sense of renewal and rejuvenation. It symbolizes the presence of divine healing energies.',
    'upright4': 'Guidance: The Star upright signifies guidance and divine assistance. It represents a connection to higher wisdom, spiritual guidance, or supportive influences that provide direction and illuminate the path ahead.',
    'upright5': 'Faith: This card embodies faith and trust in the universe. The Star represents the belief that everything happens for a reason and that there is a greater plan unfolding. It encourages having faith in yourself and the journey, knowing that you are being guided and supported.',
    'reversed1': 'Disillusionment: The Star reversed suggests a sense of disillusionment or loss of faith. It signifies a period of doubt or disappointment, where you may feel disconnected from their inner guidance or struggle to find hope and inspiration.',
    'reversed2': 'Lack of Direction: This card represents a lack of clarity or direction. The Star reversed signifies feeling lost or uncertain about the path ahead, lacking a clear vision or purpose. It may indicate a need for inner reflection and reevaluation.',
    'reversed3': 'Pessimism: The Star reversed can symbolize pessimism or a negative outlook. It suggests a tendency to focus on limitations or setbacks, losing sight of the positive aspects of life. It encourages shifting perspective and finding ways to cultivate optimism.',
    'reversed4': 'Blocked Intuition: In the reversed position, the Star signifies a disconnection from your intuition or inner guidance. It suggests difficulty accessing and trusting your intuition, resulting in a sense of confusion or being out of touch with your true self.',
    'reversed5': 'Healing Delayed: This card represents a delay in healing or the resolution of emotional or spiritual wounds. The Star reversed suggests that the process of healing may be slower or require additional effort. It encourages patience and perseverance in the journey toward inner wholeness.',
    'img': '',
  },

  // '': {
  //   'type': '',
  //   'suit': '',
  //   'cardName': '',
  //   'description': '',
  //   'upright1': '',
  //   'upright2': '',
  //   'upright3': '',
  //   'upright4': '',
  //   'upright5': '',
  //   'reversed1': '',
  //   'reversed2': '',
  //   'reversed3': '',
  //   'reversed4': '',
  //   'reversed5': '',
  //   'img': '',
  // },
  'unknown': {
    'type': 'unknown',
    'cardName': 'unknown',
    'uprightKeywords': 'unknown',
    'reversedKeywords': 'unknown',
    'description': 'unknown',
    'img': 'unknown',
  }  
}

app.get('/', (req,res)=>{
  res.sendFile(__dirname + '/index.html')
})

app.get('/api/:name', (req,res)=>{
  const tarotCards = req.params.name.toLowerCase()
  if(card[tarotCards]){
    res.json(card[tarotCards])
  }else{
    res.json(card['unknown'])
  }
})

app.listen(process.env.PORT || PORT, ()=>{
  console.log(`Woo port ${PORT} is up and running - go catch it!`)
})



